name = "lmsgen-publica-edge"
main = "src/index.js"
compatibility_date = "2026-09-17"
workers_dev = true

[vars]
ROOT_DOMAIN = "lmsgen.in"
FRONTEND_ORIGIN = "https://kahoot-awareness-frontend.onrender.com"
API_ORIGIN = "https://kahoot-awareness-backend.onrender.com"

[[routes]]
pattern = "*.lmsgen.in/*"
zone_name = "lmsgen.in"
