// Compatibility adapter retained so existing SCORM author routes and tests do not need to change.
// Course raster media is now generated by Gemini using the same server-side API key
// used for course content generation. Replicate is no longer required by this path.
const geminiMedia = require('./GeminiCourseMediaService');

function rateLimitDetail(state) {
    const seconds = Math.max(1, Math.ceil(Number(state?.waitMs || 0) / 1000));
    return `Gemini image generation is rate limited. Retry in about ${seconds}s.`;
}

function promptWasServiceAccountGenerated(provider, auth) {
    const name = String(provider || '').trim().toLowerCase();
    if (['gemini_service_account', 'vertex_ai'].includes(name)) return true;
    return name === 'gemini' && String(auth || '').trim().toLowerCase() === 'service_account';
}

module.exports = {
    ...geminiMedia,
    rateLimitDetail,
    promptWasServiceAccountGenerated,
    // Retained only for backwards-compatible imports from the previous Replicate service.
    IMAGE_UNIT_USD: 0.003
};
