// Compatibility adapter retained so existing SCORM author routes do not need to change.
// Course raster media is now generated by Gemini using the same server-side API key
// used for course content generation. Replicate is no longer required by this path.
module.exports = require('./GeminiCourseMediaService');
