/**
 * Curated course themes for generated learner courses.
 * Eight stable, selectable themes shared by the authoring API and the
 * visual finalizers. Theme 1 is the platform default/fallback.
 */
const THEMES = {
    1: {
        id: 1,
        slug: 'midnight-blue',
        name: 'Midnight Blue',
        description: 'Deep navy surfaces with crisp white type and a confident blue accent.',
        primary: '#1B3A6B',
        primaryDark: '#0F2242',
        accent: '#4C8DFF',
        accent2: '#9DC0FF',
        bg: '#0E1B33',
        bg2: '#16294D',
        surface: '#1B3A6B',
        surface2: '#24467C',
        text: '#F2F6FD',
        body: '#C7D6EE',
        muted: '#8FA3C4',
        line: '#2C4A7D',
        visualBg: '#16294D',
        visualBg2: '#0E1B33',
        visualCard: '#FFFFFF',
        visualCard2: '#EAF1FB',
        visualText: '#10233F',
        visualMuted: '#5A7194',
        soft: '#DCE8FA',
        glow: '#4C8DFF',
        motif: 'midnight'
    },
    2: {
        id: 2,
        slug: 'gamma-editorial',
        name: 'Gamma Editorial',
        description: 'Neutral paper, charcoal typography and restrained editorial highlights.',
        primary: '#282824',
        primaryDark: '#171715',
        accent: '#CBC5B8',
        accent2: '#FCF2B5',
        bg: '#E7E7E4',
        bg2: '#E5DFD2',
        surface: '#F4F2EC',
        surface2: '#E0DDD4',
        text: '#282824',
        body: '#4A4A45',
        muted: '#77776F',
        line: '#CBC5B8',
        visualBg: '#E5DFD2',
        visualBg2: '#CBC5B8',
        visualCard: '#F4F2EC',
        visualCard2: '#E7E7E4',
        visualText: '#282824',
        visualMuted: '#4A4A45',
        soft: '#FCF2B5',
        glow: '#4FC9BF',
        motif: 'editorial'
    },
    3: {
        id: 3,
        slug: 'amber-signal',
        name: 'Amber Signal',
        description: 'Warm amber accents on deep charcoal for high-attention moments.',
        primary: '#B25E09',
        primaryDark: '#7A3F06',
        accent: '#F5A524',
        accent2: '#FFD98A',
        bg: '#211708',
        bg2: '#2E2010',
        surface: '#3A2A14',
        surface2: '#4A3619',
        text: '#FDF6E7',
        body: '#E8D5B5',
        muted: '#B99B6E',
        line: '#5A4426',
        visualBg: '#2E2010',
        visualBg2: '#211708',
        visualCard: '#FFFFFF',
        visualCard2: '#FBF3E2',
        visualText: '#3A2408',
        visualMuted: '#7A6238',
        soft: '#FFE9BD',
        glow: '#F5A524',
        motif: 'signal'
    },
    4: {
        id: 4,
        slug: 'emerald-atlas',
        name: 'Emerald Atlas',
        description: 'Deep emerald surfaces with fresh mint highlights and calm contrast.',
        primary: '#0E6B4F',
        primaryDark: '#084733',
        accent: '#34D399',
        accent2: '#A7F3D0',
        bg: '#0A2420',
        bg2: '#0E332C',
        surface: '#134840',
        surface2: '#18594F',
        text: '#EAFBF3',
        body: '#BFE6D4',
        muted: '#7FA895',
        line: '#1F5A4D',
        visualBg: '#0E332C',
        visualBg2: '#0A2420',
        visualCard: '#FFFFFF',
        visualCard2: '#E9F7F0',
        visualText: '#0B3B2E',
        visualMuted: '#527A6A',
        soft: '#D3F5E4',
        glow: '#34D399',
        motif: 'atlas'
    },
    5: {
        id: 5,
        slug: 'modern-rose',
        name: 'Modern Rose',
        description: 'Soft rose tones with rich plum type for a contemporary feel.',
        primary: '#9D2C5B',
        primaryDark: '#671B3D',
        accent: '#F472A7',
        accent2: '#FBC4D8',
        bg: '#2A1220',
        bg2: '#3A1829',
        surface: '#4A2036',
        surface2: '#5A2843',
        text: '#FDF0F5',
        body: '#EBC9D8',
        muted: '#B98AA0',
        line: '#5E2C44',
        visualBg: '#3A1829',
        visualBg2: '#2A1220',
        visualCard: '#FFFFFF',
        visualCard2: '#FBEFF4',
        visualText: '#571B38',
        visualMuted: '#96617E',
        soft: '#FBDCE8',
        glow: '#F472A7',
        motif: 'rose'
    },
    6: {
        id: 6,
        slug: 'arctic-teal',
        name: 'Arctic Teal',
        description: 'Crisp arctic whites with deep teal structure and aqua light.',
        primary: '#0F766E',
        primaryDark: '#0A4F4A',
        accent: '#4FC9BF',
        accent2: '#A7E8E2',
        bg: '#EAF4F2',
        bg2: '#DCEBE8',
        surface: '#FFFFFF',
        surface2: '#F2F9F8',
        text: '#0B2E2B',
        body: '#335652',
        muted: '#6E8F8B',
        line: '#BFD9D5',
        visualBg: '#DCEBE8',
        visualBg2: '#C4DDD8',
        visualCard: '#FFFFFF',
        visualCard2: '#EAF4F2',
        visualText: '#0B2E2B',
        visualMuted: '#4A6B67',
        soft: '#D2F0EC',
        glow: '#4FC9BF',
        motif: 'arctic'
    },
    7: {
        id: 7,
        slug: 'violet-horizon',
        name: 'Violet Horizon',
        description: 'Twilight violet gradients with luminous lavender accents.',
        primary: '#6D28D9',
        primaryDark: '#471A8F',
        accent: '#A78BFA',
        accent2: '#D6C6FB',
        bg: '#1D1433',
        bg2: '#281C47',
        surface: '#35265C',
        surface2: '#5A2843',
        text: '#F3EEFD',
        body: '#CFC2EE',
        muted: '#9A86C6',
        line: '#45336F',
        visualBg: '#281C47',
        visualBg2: '#1D1433',
        visualCard: '#FFFFFF',
        visualCard2: '#F1EBFD',
        visualText: '#2E1A5E',
        visualMuted: '#6E5A9E',
        soft: '#E2D6FA',
        glow: '#A78BFA',
        motif: 'horizon'
    },
    8: {
        id: 8,
        slug: 'charcoal-slate',
        name: 'Charcoal Slate',
        description: 'Monochrome charcoal with a single confident highlight.',
        primary: '#3A3F45',
        primaryDark: '#22262B',
        accent: '#9AA3AD',
        accent2: '#D5DAE0',
        bg: '#F4F5F6',
        bg2: '#E8EAED',
        surface: '#FFFFFF',
        surface2: '#F7F8F9',
        text: '#22262B',
        body: '#4A5058',
        muted: '#7A828B',
        line: '#D5DAE0',
        visualBg: '#E8EAED',
        visualBg2: '#D5DAE0',
        visualCard: '#FFFFFF',
        visualCard2: '#F4F5F6',
        visualText: '#22262B',
        visualMuted: '#5A6169',
        soft: '#EDEFF1',
        glow: '#9AA3AD',
        motif: 'slate'
    }
};

function normalizeThemeId(value) {
    const id = Number(value);
    if (Number.isInteger(id) && id >= 1 && id <= 8) return id;
    return 1;
}

function getTheme(value) {
    return THEMES[normalizeThemeId(value)] || THEMES[1];
}

function listThemes() {
    return Object.values(THEMES).map((theme) => ({ ...theme }));
}

module.exports = {
    THEMES,
    getTheme,
    listThemes,
    normalizeThemeId
};
