'use strict';

const STYLE_ID = 'quizmoto-highly-interactive-sidebar-v4';
const SCRIPT_ID = 'quizmoto-highly-interactive-sidebar-script-v4';

function style() {
    return `<style id="${STYLE_ID}">
.qmx-course-body{display:flex;flex:1 1 auto;min-height:0;min-width:0;overflow:hidden;position:relative}
.qmx-course-main{flex:1 1 auto;min-width:0;min-height:0;position:relative}
.qmx-course-sidebar{display:none}
body[data-qmx-course-template="highly-interactive"] footer{height:78px!important;min-height:78px!important;padding:12px 28px 14px!important;align-items:center!important}
body[data-qmx-course-template="highly-interactive"] footer .nav-btn{min-height:46px!important;padding:11px 20px!important}
body[data-qmx-course-template="highly-interactive"] #next-btn[data-qmx-interaction-locked="true"]{visibility:hidden!important;pointer-events:none!important}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-source{display:none!important;visibility:hidden!important;pointer-events:none!important;height:0!important;min-height:0!important;margin:0!important;padding:0!important;overflow:hidden!important}
body[data-qmx-course-template="highly-interactive"] .slide[data-qmx-interaction="focus_reveal"] .qmx-cards,
body[data-qmx-course-template="highly-interactive"] .slide[data-qmx-interaction="focus_reveal"] .qmx-static-cards{display:none!important}
body[data-qmx-course-template="highly-interactive"] .qmx-focus-trigger{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-height:48px!important;margin:22px 0 18px!important;padding:12px 22px!important;border-radius:999px!important;line-height:1.1!important;white-space:nowrap!important}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-instruction{display:flex;align-items:center;gap:8px;margin-top:12px;font-size:11px;line-height:1.35;font-weight:650;color:var(--ink-soft,#49625e)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-instruction::before{content:'↗';display:grid;place-items:center;width:21px;height:21px;flex:0 0 21px;border-radius:50%;background:var(--soft,#dff4f0);color:var(--primary-dark,#087f75);font-size:10px;font-weight:800}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-instruction.is-complete{color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-instruction.is-complete::before{content:'✓';background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-template-rows:repeat(2,minmax(112px,1fr))!important;gap:12px!important;width:100%!important;max-width:100%!important;margin-top:18px!important;align-items:stretch!important}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card{position:relative;min-width:0;min-height:112px;padding:0;border:0;background:transparent;perspective:1200px;cursor:pointer;text-align:left}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card-inner{position:relative;display:grid;width:100%;height:100%;min-height:112px;transform-style:preserve-3d;transition:transform .48s cubic-bezier(.2,.72,.22,1)}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card.is-revealed .qmx-reveal-card-inner{transform:rotateY(180deg)}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-face{grid-area:1/1;display:flex;flex-direction:column;align-items:flex-start;min-width:0;min-height:112px;padding:16px 17px;border:1px solid var(--paper-3,#d8e5e2);border-radius:14px;background:var(--surface,#fff);backface-visibility:hidden;-webkit-backface-visibility:hidden;box-shadow:0 8px 20px rgba(15,23,42,.045);overflow:hidden}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-back{transform:rotateY(180deg);border-color:var(--primary,#119286);background:var(--soft,#edf8f6)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-number{display:grid;place-items:center;width:30px;height:30px;min-width:30px;margin-bottom:12px;border:1px solid var(--paper-3,#d8e5e2);border-radius:9px;background:var(--paper,#f3f8f7);color:var(--primary-dark,#087f75);font-size:10px;font-weight:800}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card[data-qmx-revealed="true"] .qmx-interaction-number{border-color:var(--primary,#119286);background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-label{font-size:15px;line-height:1.28;font-weight:700;color:var(--ink,#10211f)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-detail{font-size:13.5px;line-height:1.46;font-weight:540;color:var(--ink,#10211f)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-hint{margin-top:auto;padding-top:12px;font-size:9px;line-height:1.2;text-transform:uppercase;letter-spacing:.08em;font-weight:800;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card:hover .qmx-reveal-face,body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card:focus-visible .qmx-reveal-face{border-color:var(--primary,#119286)}
body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card:focus-visible{outline:2px solid var(--primary,#119286);outline-offset:3px;border-radius:14px}
body[data-qmx-course-template="highly-interactive"] .qmx-step-grid-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-explore-grid-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-compare-grid-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-decision-grid-v2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;width:100%;margin-top:18px}
body[data-qmx-course-template="highly-interactive"] .qmx-step-option,
body[data-qmx-course-template="highly-interactive"] .qmx-explore-option-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-compare-option,
body[data-qmx-course-template="highly-interactive"] .qmx-decision-option{display:grid;grid-template-columns:34px minmax(0,1fr);grid-template-rows:auto auto;column-gap:11px;row-gap:4px;align-items:center;min-height:86px;padding:12px 14px;border:1px solid var(--paper-3,#d8e5e2);border-radius:13px;background:var(--surface,#fff);color:var(--ink,#10211f);text-align:left;cursor:pointer;transition:border-color .18s ease,background .18s ease,transform .18s ease}
body[data-qmx-course-template="highly-interactive"] .qmx-step-option:hover,body[data-qmx-course-template="highly-interactive"] .qmx-explore-option-v2:hover,body[data-qmx-course-template="highly-interactive"] .qmx-compare-option:hover,body[data-qmx-course-template="highly-interactive"] .qmx-decision-option:hover,body[data-qmx-course-template="highly-interactive"] .qmx-step-option:focus-visible,body[data-qmx-course-template="highly-interactive"] .qmx-explore-option-v2:focus-visible,body[data-qmx-course-template="highly-interactive"] .qmx-compare-option:focus-visible,body[data-qmx-course-template="highly-interactive"] .qmx-decision-option:focus-visible{border-color:var(--primary,#119286);outline:none}
body[data-qmx-course-template="highly-interactive"] .qmx-step-option.is-selected,body[data-qmx-course-template="highly-interactive"] .qmx-explore-option-v2.is-selected,body[data-qmx-course-template="highly-interactive"] .qmx-compare-option.is-selected,body[data-qmx-course-template="highly-interactive"] .qmx-decision-option.is-selected{border-color:var(--primary,#119286);background:var(--soft,#dff4f0);transform:translateY(-1px)}
body[data-qmx-course-template="highly-interactive"] .qmx-option-number{grid-row:1/span 2;display:grid;place-items:center;width:32px;height:32px;border:1px solid var(--paper-3,#d8e5e2);border-radius:9px;background:var(--paper,#f3f8f7);color:var(--primary-dark,#087f75);font-size:10px;font-weight:800}
body[data-qmx-course-template="highly-interactive"] [data-qmx-step-visited="true"] .qmx-option-number,body[data-qmx-course-template="highly-interactive"] [data-qmx-explore-visited="true"] .qmx-option-number,body[data-qmx-course-template="highly-interactive"] [data-qmx-compare-visited="true"] .qmx-option-number,body[data-qmx-course-template="highly-interactive"] [data-qmx-decision-selected="true"] .qmx-option-number{border-color:var(--primary,#119286);background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="highly-interactive"] .qmx-option-label{min-width:0;font-size:13px;line-height:1.28;font-weight:700;color:var(--ink,#10211f);display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
body[data-qmx-course-template="highly-interactive"] .qmx-option-hint{font-size:8.5px;line-height:1.2;text-transform:uppercase;letter-spacing:.075em;font-weight:800;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-panel{margin-top:12px;padding:15px 17px;border:1px solid var(--paper-3,#d8e5e2);border-radius:14px;background:var(--surface,#fff)}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-panel-label{font-size:9px;line-height:1.2;text-transform:uppercase;letter-spacing:.09em;color:var(--primary-dark,#087f75);font-weight:800}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-panel p{margin:7px 0 0!important;font-size:13.5px!important;line-height:1.46!important;color:var(--ink,#10211f)!important;font-weight:550!important}
body[data-qmx-course-template="highly-interactive"] .qmx-learning-shell.has-image .qmx-interaction-grid,
body[data-qmx-course-template="highly-interactive"] .qmx-learning-shell.has-image .qmx-step-grid-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-learning-shell.has-image .qmx-explore-grid-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-learning-shell.has-image .qmx-compare-grid-v2,
body[data-qmx-course-template="highly-interactive"] .qmx-learning-shell.has-image .qmx-decision-grid-v2{grid-template-columns:repeat(2,minmax(0,1fr))!important}
@media(min-width:1500px){
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar{display:flex;flex:0 0 252px;width:252px;min-width:252px;min-height:0;flex-direction:column;border-right:1px solid var(--paper-3,#d8e5e2);background:linear-gradient(180deg,var(--surface,#fff) 0%,var(--paper,#f3f8f7) 100%);color:var(--ink,#10211f);box-shadow:10px 0 28px rgba(15,52,48,.035);z-index:12;overflow:hidden}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-head{padding:20px 18px 15px;border-bottom:1px solid var(--paper-3,#d8e5e2)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-kicker{font-size:9px;line-height:1;text-transform:uppercase;letter-spacing:.11em;font-weight:800;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-title{margin-top:8px;font-size:14px;line-height:1.28;font-weight:750;color:var(--ink,#10211f);display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-progress{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:13px;font-size:10px;color:var(--ink-soft,#49625e)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-progress strong{font-size:10px;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-list{flex:1 1 auto;min-height:0;width:100%;max-width:100%;overflow-y:auto;overflow-x:hidden;overscroll-behavior-x:none;padding:12px 10px 16px;scrollbar-width:thin;scrollbar-color:rgba(17,109,99,.25) transparent}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-list::-webkit-scrollbar{width:6px;height:0}
body[data-qmx-course-template="highly-interactive"] .qmx-course-sidebar-list::-webkit-scrollbar-thumb{background:rgba(17,109,99,.24);border-radius:999px}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-item{width:100%;max-width:100%;min-width:0;box-sizing:border-box;display:grid;grid-template-columns:32px minmax(0,1fr) 18px;align-items:center;gap:9px;margin:3px 0;padding:9px 8px;border:0;border-radius:11px;background:transparent;color:var(--ink-soft,#49625e);text-align:left;cursor:default;overflow:hidden;transition:background .18s ease,color .18s ease}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-item.is-visited{cursor:pointer;color:var(--ink,#10211f)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-item.is-visited:hover{background:rgba(17,146,134,.075)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-item.is-active{background:var(--soft,#dff4f0);color:var(--ink,#10211f);box-shadow:inset 3px 0 0 var(--primary,#119286)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-number{width:30px;height:30px;min-width:30px;display:grid;place-items:center;border:1px solid var(--paper-3,#d8e5e2);border-radius:10px;background:var(--surface,#fff);font-size:10px;line-height:1;font-weight:800;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-item.is-active .qmx-course-nav-number{border-color:var(--primary,#119286);background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-copy{display:block;min-width:0;overflow:hidden}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-type{display:block;font-size:8px;line-height:1.1;text-transform:uppercase;letter-spacing:.07em;font-weight:750;color:var(--primary-dark,#087f75);opacity:.72;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-label{display:-webkit-box;margin-top:3px;font-size:11px;line-height:1.28;font-weight:620;white-space:normal;overflow:hidden;text-overflow:ellipsis;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow-wrap:anywhere}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-state{display:grid;place-items:center;min-width:0;font-size:11px;font-weight:800;color:var(--primary,#119286);text-align:center}
body[data-qmx-course-template="highly-interactive"] .qmx-course-nav-item:not(.is-visited):not(.is-active){opacity:.58}
body[data-qmx-course-template="highly-interactive"] .qmx-copy h2{font-size:clamp(38px,3.25vw,56px)!important;max-width:900px!important}
body[data-qmx-course-template="highly-interactive"] .qmx-copy>p{font-size:16px!important;line-height:1.54!important;max-width:840px!important}
body[data-qmx-course-template="highly-interactive"] .qmx-learning-shell.has-image .qmx-native-media{height:min(80%,540px)!important;min-height:320px!important}
body[data-qmx-course-template="highly-interactive"] .qmx-interaction-label{font-size:15.5px}
}
@media(max-width:900px){body[data-qmx-course-template="highly-interactive"] .qmx-interaction-grid,body[data-qmx-course-template="highly-interactive"] .qmx-step-grid-v2,body[data-qmx-course-template="highly-interactive"] .qmx-explore-grid-v2,body[data-qmx-course-template="highly-interactive"] .qmx-compare-grid-v2,body[data-qmx-course-template="highly-interactive"] .qmx-decision-grid-v2{grid-template-columns:1fr!important;grid-template-rows:auto!important}}
@media(max-height:720px){body[data-qmx-course-template="highly-interactive"] footer{height:70px!important;min-height:70px!important;padding:9px 22px 11px!important}body[data-qmx-course-template="highly-interactive"] .qmx-reveal-face{min-height:96px;padding:12px 14px}body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card,body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card-inner{min-height:96px}}
@media(prefers-reduced-motion:reduce){body[data-qmx-course-template="highly-interactive"] .qmx-reveal-card-inner{transition:none!important}}
</style>`;
}

function script() {
    return `<script id="${SCRIPT_ID}">
(function(){
  var state={maxVisited:0,lastIndex:-1,navigating:false};
  var stopWords={a:1,an:1,the:1,and:1,or:1,but:1,is:1,are:1,was:1,were:1,be:1,been:1,being:1,to:1,of:1,for:1,in:1,on:1,with:1,from:1,as:1,at:1,by:1,can:1,could:1,may:1,might:1,will:1,would:1,should:1,this:1,that:1,these:1,those:1,it:1,its:1,they:1,them:1,their:1,you:1,your:1,we:1,our:1,then:1,also:1,very:1};
  function make(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
  function clean(value){return String(value||'').replace(/\\s+/g,' ').trim();}
  function slides(){return Array.prototype.slice.call(document.querySelectorAll('main .slide'));}
  function activeSlide(){return document.querySelector('main .slide.active');}
  function activeIndex(){var list=slides(),active=activeSlide();return Math.max(0,list.indexOf(active));}
  function courseTitle(){var h=document.querySelector('#app>header h1,header h1'),cover=document.querySelector('.slide[data-kind="cover"] h2');return clean((h&&h.textContent)||(cover&&cover.textContent)||'Course contents');}
  function itemMeta(slide,index,quizNo){var kind=String(slide.getAttribute('data-kind')||'learning');if(kind==='cover')return {type:'Start',label:'Introduction'};if(kind==='final')return {type:'Finish',label:'Course complete'};if(kind==='quiz')return {type:'Knowledge check',label:'Question '+String(quizNo).padStart(2,'0')};var heading=slide.querySelector('.qmx-copy h2,h2');return {type:'Learning',label:clean(heading&&heading.textContent)||('Learning section '+index)};}
  function detailFrom(node){var p=node&&node.querySelector?node.querySelector('p'):null;return clean((p&&p.textContent)||(node&&node.textContent));}
  function trimLead(value){return clean(value).replace(/^(instead|however|first|next|then|finally|also|remember|note|a|an|the|this|these|those|they|it|you|your)\\b[,:\\s-]*/i,'').trim();}
  function labelFrom(value,index){var source=clean(value).replace(/^[0-9]+[.)\\s-]*/,'').replace(/[.!?]+$/,'');if(!source)return 'Key point '+String(index+1).padStart(2,'0');var pieces=source.split(/[,:;–—]/).map(trimLead).filter(Boolean);for(var i=0;i<pieces.length;i++){var pw=pieces[i].split(/\\s+/);if(pw.length>=2&&pw.length<=6&&pieces[i].length<=58)return pieces[i];}var words=trimLead(source).split(/\\s+/),picked=[],seen={};for(var j=0;j<words.length&&picked.length<5;j++){var raw=words[j].replace(/[^A-Za-z0-9'-]/g,'');var key=raw.toLowerCase();if(!raw||stopWords[key]||seen[key])continue;seen[key]=1;picked.push(raw);}var label=picked.join(' ');if(!label)label=words.slice(0,5).join(' ');return label.charAt(0).toUpperCase()+label.slice(1);}
  function notify(slide){try{slide.dispatchEvent(new CustomEvent('qmx:interaction-update',{bubbles:true}));}catch(e){var ev=document.createEvent('Event');ev.initEvent('qmx:interaction-update',true,true);slide.dispatchEvent(ev);}}
  function instruction(copy,text){var n=make('div','qmx-interaction-instruction',text);copy.appendChild(n);return n;}
  function markSource(node){if(!node)return;node.classList.remove('qmx-cards');node.classList.add('qmx-interaction-source');}
  function sourceCards(slide){return Array.prototype.slice.call(slide.querySelectorAll('.qmx-cards .qmx-card,.qmx-static-cards .qmx-card'));}
  function updateProgress(note,count,total,verb){if(!note)return;var complete=count>=total&&total>0;note.classList.toggle('is-complete',complete);note.textContent=complete?'All '+verb+' completed • Next is unlocked':count+' of '+total+' '+verb+' • complete all to continue';}
  function prepareFocus(slide){if(slide.getAttribute('data-qmx-owned-interaction')==='focus_reveal')return;slide.setAttribute('data-qmx-owned-interaction','focus_reveal');var copy=slide.querySelector('.qmx-copy'),trigger=slide.querySelector('.qmx-focus-trigger');if(!copy||!trigger)return;Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards,.qmx-static-cards'),markSource);var note=instruction(copy,'Reveal the key takeaways to continue');trigger.addEventListener('click',function(){slide.setAttribute('data-qmx-focus-complete','true');note.classList.add('is-complete');note.textContent='Key takeaways reviewed • Next is unlocked';notify(slide);});}
  function prepareClickReveal(slide){if(slide.getAttribute('data-qmx-owned-interaction')==='click_reveal')return;var source=slide.querySelector('.qmx-cards,.qmx-static-cards'),cards=sourceCards(slide),copy=slide.querySelector('.qmx-copy');if(!source||!cards.length||!copy)return;slide.setAttribute('data-qmx-owned-interaction','click_reveal');var items=cards.map(function(card,i){return {detail:detailFrom(card),label:labelFrom(detailFrom(card),i)};});markSource(source);var grid=make('div','qmx-interaction-grid qmx-flip-grid-v2');copy.insertBefore(grid,source);var note=instruction(copy,'Reveal all '+items.length+' cards to continue');function syncNote(){var visited=grid.querySelectorAll('.qmx-reveal-card[data-qmx-revealed="true"]').length;updateProgress(note,visited,items.length,'cards');}items.forEach(function(item,i){var button=make('button','qmx-reveal-card');button.type='button';button.setAttribute('data-qmx-revealed','false');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Reveal '+item.label);var inner=make('span','qmx-reveal-card-inner'),front=make('span','qmx-reveal-face qmx-reveal-front'),back=make('span','qmx-reveal-face qmx-reveal-back');front.appendChild(make('span','qmx-interaction-number',String(i+1).padStart(2,'0')));front.appendChild(make('span','qmx-interaction-label',item.label));front.appendChild(make('span','qmx-interaction-hint','Click to reveal'));back.appendChild(make('span','qmx-interaction-number',String(i+1).padStart(2,'0')));back.appendChild(make('span','qmx-interaction-detail',item.detail));back.appendChild(make('span','qmx-interaction-hint','Click to flip back'));inner.appendChild(front);inner.appendChild(back);button.appendChild(inner);button.onclick=function(){var open=!button.classList.contains('is-revealed');button.classList.toggle('is-revealed',open);button.setAttribute('aria-expanded',open?'true':'false');if(open)button.setAttribute('data-qmx-revealed','true');syncNote();notify(slide);};grid.appendChild(button);});syncNote();}
  function optionButton(cls,index,label,hint){var b=make('button',cls);b.type='button';b.appendChild(make('span','qmx-option-number',String(index+1).padStart(2,'0')));b.appendChild(make('span','qmx-option-label',label));b.appendChild(make('span','qmx-option-hint',hint));return b;}
  function panel(copy,labelText,prompt){var p=make('div','qmx-interaction-panel'),label=make('div','qmx-interaction-panel-label',labelText),detail=make('p','',prompt);p.appendChild(label);p.appendChild(detail);copy.appendChild(p);return {panel:p,label:label,detail:detail};}
  function prepareStep(slide){if(slide.getAttribute('data-qmx-owned-interaction')==='step_explore')return;var source=slide.querySelector('.qmx-process'),steps=source?Array.prototype.slice.call(source.querySelectorAll('.qmx-step')):[],copy=slide.querySelector('.qmx-copy');if(!source||!steps.length||!copy)return;slide.setAttribute('data-qmx-owned-interaction','step_explore');var items=steps.map(function(step,i){var d=detailFrom(step);return {detail:d,label:labelFrom(d,i)};});source.classList.add('qmx-interaction-source');var grid=make('div','qmx-step-grid-v2');copy.insertBefore(grid,source);var info=panel(copy,'Explore the steps','Select each step to reveal its guidance.');var note=instruction(copy,'Explore all '+items.length+' steps to continue');function syncNote(){var visited=grid.querySelectorAll('.qmx-step-option[data-qmx-step-visited="true"]').length;updateProgress(note,visited,items.length,'steps');}items.forEach(function(item,i){var b=optionButton('qmx-step-option',i,item.label,'Select to explore');b.setAttribute('data-qmx-step-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.querySelectorAll('.qmx-step-option'),function(x){x.classList.remove('is-selected');});b.classList.add('is-selected');b.setAttribute('data-qmx-step-visited','true');info.label.textContent='Step '+String(i+1).padStart(2,'0');info.detail.textContent=item.detail;syncNote();notify(slide);};grid.appendChild(b);});syncNote();}
  function prepareGuided(slide){if(slide.getAttribute('data-qmx-owned-interaction')==='hotspot_explore')return;var copy=slide.querySelector('.qmx-copy'),cards=sourceCards(slide);if(!copy||!cards.length)return;slide.setAttribute('data-qmx-owned-interaction','hotspot_explore');Array.prototype.forEach.call(slide.querySelectorAll('.qmx-explore-grid,.qmx-hotspot-panel'),function(n){n.remove();});Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards,.qmx-static-cards'),markSource);var items=cards.slice(0,4).map(function(card,i){var d=detailFrom(card);return {detail:d,label:labelFrom(d,i)};}),grid=make('div','qmx-explore-grid-v2');copy.appendChild(grid);var info=panel(copy,'Explore the signs','Select each item to reveal the guidance.');var note=instruction(copy,'Explore all '+items.length+' points to continue');function syncNote(){var visited=grid.querySelectorAll('.qmx-explore-option-v2[data-qmx-explore-visited="true"]').length;updateProgress(note,visited,items.length,'points');}items.forEach(function(item,i){var b=optionButton('qmx-explore-option-v2',i,item.label,'Select to explore');b.setAttribute('data-qmx-explore-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.querySelectorAll('.qmx-explore-option-v2'),function(x){x.classList.remove('is-selected');});b.classList.add('is-selected');b.setAttribute('data-qmx-explore-visited','true');info.label.textContent='Point '+String(i+1).padStart(2,'0');info.detail.textContent=item.detail;syncNote();notify(slide);};grid.appendChild(b);});syncNote();}
  function prepareCompare(slide){if(slide.getAttribute('data-qmx-owned-interaction')==='compare_reveal')return;var copy=slide.querySelector('.qmx-copy'),source=slide.querySelector('.qmx-compare');if(!copy||!source)return;var cols=Array.prototype.slice.call(source.querySelectorAll('.qmx-compare-col'));if(!cols.length)return;slide.setAttribute('data-qmx-owned-interaction','compare_reveal');var items=cols.map(function(col,i){var d=detailFrom(col);return {detail:d,label:labelFrom(d,i)};});source.classList.add('qmx-interaction-source');var grid=make('div','qmx-compare-grid-v2');copy.insertBefore(grid,source);var info=panel(copy,'Compare the points','Select each point to reveal the comparison detail.');var note=instruction(copy,'Review all '+items.length+' comparison points to continue');function syncNote(){var visited=grid.querySelectorAll('.qmx-compare-option[data-qmx-compare-visited="true"]').length;updateProgress(note,visited,items.length,'comparison points');}items.forEach(function(item,i){var b=optionButton('qmx-compare-option',i,item.label,'Select to compare');b.setAttribute('data-qmx-compare-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.querySelectorAll('.qmx-compare-option'),function(x){x.classList.remove('is-selected');});b.classList.add('is-selected');b.setAttribute('data-qmx-compare-visited','true');info.label.textContent='Comparison '+String(i+1).padStart(2,'0');info.detail.textContent=item.detail;syncNote();notify(slide);};grid.appendChild(b);});syncNote();}
  function prepareDecision(slide){if(slide.getAttribute('data-qmx-owned-interaction')==='decision_explore')return;var copy=slide.querySelector('.qmx-copy'),cards=sourceCards(slide);if(!copy||!cards.length)return;slide.setAttribute('data-qmx-owned-interaction','decision_explore');Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards,.qmx-static-cards'),markSource);var items=cards.map(function(card,i){var d=detailFrom(card);return {detail:d,label:labelFrom(d,i)};}),grid=make('div','qmx-decision-grid-v2');copy.appendChild(grid);var info=panel(copy,'Your selection','Select an option to reveal its guidance.');var note=instruction(copy,'Select an option to continue');items.forEach(function(item,i){var b=optionButton('qmx-decision-option',i,item.label,'Select to explore');b.setAttribute('data-qmx-decision-selected','false');b.onclick=function(){Array.prototype.forEach.call(grid.querySelectorAll('.qmx-decision-option'),function(x){x.classList.remove('is-selected');x.setAttribute('data-qmx-decision-selected','false');});b.classList.add('is-selected');b.setAttribute('data-qmx-decision-selected','true');slide.setAttribute('data-qmx-decision-complete','true');info.label.textContent='Selected option '+String(i+1).padStart(2,'0');info.detail.textContent=item.detail;note.classList.add('is-complete');note.textContent='Option reviewed • Next is unlocked';notify(slide);};grid.appendChild(b);});}
  function prepareInteractions(){slides().forEach(function(slide){if(slide.getAttribute('data-kind')!=='learning')return;var type=String(slide.getAttribute('data-qmx-interaction')||'');if(type==='focus_reveal')prepareFocus(slide);else if(type==='click_reveal')prepareClickReveal(slide);else if(type==='step_explore')prepareStep(slide);else if(type==='hotspot_explore')prepareGuided(slide);else if(type==='compare_reveal')prepareCompare(slide);else if(type==='decision_explore')prepareDecision(slide);});}
  function allMarked(list,attr){return list.length>0&&Array.prototype.every.call(list,function(node){return node.getAttribute(attr)==='true';});}
  function gateStatus(slide){if(!slide)return {required:false,complete:true};if(slide.getAttribute('data-qmx-interaction-complete')==='true')return {required:true,complete:true};var kind=String(slide.getAttribute('data-kind')||'');if(kind==='quiz')return {required:true,complete:Boolean(slide.querySelector('.quiz-option.correct,.quiz-option.incorrect,[aria-checked="true"]'))};if(kind!=='learning')return {required:false,complete:true};var type=String(slide.getAttribute('data-qmx-interaction')||'');if(type==='focus_reveal'){var trigger=slide.querySelector('.qmx-focus-trigger');return trigger?{required:true,complete:slide.getAttribute('data-qmx-focus-complete')==='true'}:{required:false,complete:true};}if(type==='click_reveal'){var flips=slide.querySelectorAll('.qmx-reveal-card');return flips.length?{required:true,complete:allMarked(flips,'data-qmx-revealed')}:{required:false,complete:true};}if(type==='step_explore'){var steps=slide.querySelectorAll('.qmx-step-option');return steps.length?{required:true,complete:allMarked(steps,'data-qmx-step-visited')}:{required:false,complete:true};}if(type==='hotspot_explore'){var explore=slide.querySelectorAll('.qmx-explore-option-v2');return explore.length?{required:true,complete:allMarked(explore,'data-qmx-explore-visited')}:{required:false,complete:true};}if(type==='compare_reveal'){var compare=slide.querySelectorAll('.qmx-compare-option');return compare.length?{required:true,complete:allMarked(compare,'data-qmx-compare-visited')}:{required:false,complete:true};}if(type==='decision_explore'){var decision=slide.querySelectorAll('.qmx-decision-option');return decision.length?{required:true,complete:slide.getAttribute('data-qmx-decision-complete')==='true'}:{required:false,complete:true};}return {required:false,complete:true};}
  function syncNextGate(){var next=document.getElementById('next-btn'),slide=activeSlide();if(!next||!slide)return;next.removeAttribute('data-qmx-reveal-locked');var status=gateStatus(slide),locked=status.required&&!status.complete;slide.setAttribute('data-qmx-interaction-gated',status.required?'true':'false');if(status.required&&status.complete)slide.setAttribute('data-qmx-interaction-complete','true');if(locked){next.disabled=true;next.setAttribute('data-qmx-interaction-locked','true');next.setAttribute('aria-hidden','true');}else{next.removeAttribute('data-qmx-interaction-locked');next.removeAttribute('aria-hidden');next.disabled=false;}}
  function syncGateSoon(){syncNextGate();setTimeout(syncNextGate,0);setTimeout(syncNextGate,80);setTimeout(syncNextGate,180);}
  function build(){if(document.querySelector('.qmx-course-sidebar'))return;var main=document.querySelector('main');if(!main||!main.parentNode)return;var list=slides();if(!list.length)return;var holder=make('div','qmx-course-body');main.parentNode.insertBefore(holder,main);var aside=make('aside','qmx-course-sidebar');aside.setAttribute('aria-label','Course contents');var head=make('div','qmx-course-sidebar-head');head.appendChild(make('div','qmx-course-sidebar-kicker','Course contents'));head.appendChild(make('div','qmx-course-sidebar-title',courseTitle()));var prog=make('div','qmx-course-sidebar-progress');prog.appendChild(make('span','','Your progress'));var progValue=make('strong','qmx-course-sidebar-progress-value','Part 1 of '+list.length);prog.appendChild(progValue);head.appendChild(prog);aside.appendChild(head);var nav=make('nav','qmx-course-sidebar-list');var quizNo=0;list.forEach(function(slide,i){if(slide.getAttribute('data-kind')==='quiz')quizNo+=1;var meta=itemMeta(slide,i,quizNo),button=make('button','qmx-course-nav-item');button.type='button';button.setAttribute('data-qmx-target',String(i));button.setAttribute('aria-label','Go to '+meta.label);button.title=meta.label;button.appendChild(make('span','qmx-course-nav-number',String(i+1).padStart(2,'0')));var copy=make('span','qmx-course-nav-copy');copy.appendChild(make('span','qmx-course-nav-type',meta.type));copy.appendChild(make('span','qmx-course-nav-label',meta.label));button.appendChild(copy);button.appendChild(make('span','qmx-course-nav-state',''));button.onclick=function(){navigate(Number(button.getAttribute('data-qmx-target')));};nav.appendChild(button);});aside.appendChild(nav);holder.appendChild(aside);holder.appendChild(main);main.classList.add('qmx-course-main');}
  function sync(force){var list=slides(),idx=activeIndex();state.maxVisited=Math.max(state.maxVisited,idx);syncNextGate();if(!force&&idx===state.lastIndex)return;state.lastIndex=idx;var value=document.querySelector('.qmx-course-sidebar-progress-value');if(value)value.textContent='Part '+(idx+1)+' of '+list.length;Array.prototype.forEach.call(document.querySelectorAll('.qmx-course-nav-item'),function(button){var target=Number(button.getAttribute('data-qmx-target')),active=target===idx,visited=target<=state.maxVisited;button.classList.toggle('is-active',active);button.classList.toggle('is-visited',visited);button.disabled=!visited&&!active;button.setAttribute('aria-current',active?'step':'false');var mark=button.querySelector('.qmx-course-nav-state');if(mark)mark.textContent=active?'•':(target<state.maxVisited?'✓':'');});}
  function navigate(target){if(state.navigating||!Number.isFinite(target)||target<0||target>state.maxVisited)return;state.navigating=true;var guard=0;function done(){state.navigating=false;sync(true);if(typeof window.requestAnimationFrame==='function')requestAnimationFrame(function(){window.dispatchEvent(new Event('resize'));});}function step(){var current=activeIndex();if(current===target||guard++>40){done();return;}var id=target<current?'prev-btn':'next-btn',button=document.getElementById(id);if(!button||button.disabled||getComputedStyle(button).display==='none'){done();return;}var before=current;button.click();setTimeout(function(){if(activeIndex()===before){done();return;}step();},45);}step();}
  function seedResume(){var idx=activeIndex();slides().forEach(function(slide,i){if(i<idx)slide.setAttribute('data-qmx-interaction-complete','true');});state.maxVisited=Math.max(state.maxVisited,idx);}
  function install(){if(!document.body||document.body.getAttribute('data-qmx-course-template')!=='highly-interactive')return;prepareInteractions();build();seedResume();sync(true);var main=document.querySelector('main');if(main){var observer=new MutationObserver(function(changes){var navChanged=changes.some(function(change){return change.type==='attributes'&&change.attributeName==='class'&&change.target&&change.target.classList&&change.target.classList.contains('slide');});if(navChanged){prepareInteractions();sync(false);}else syncNextGate();});observer.observe(main,{subtree:true,childList:true,attributes:true,attributeFilter:['class','data-qmx-revealed','data-qmx-step-visited','data-qmx-explore-visited','data-qmx-compare-visited','data-qmx-decision-complete']});}document.addEventListener('qmx:interaction-update',syncGateSoon,true);document.addEventListener('click',function(){setTimeout(function(){sync(false);syncNextGate();},0);},true);window.addEventListener('load',function(){setTimeout(function(){prepareInteractions();syncNextGate();},0);});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
</script>`;
}

function inject(html, templateId) {
    let source = String(html || '');
    if (!source || String(templateId || '') !== 'highly-interactive') return source;
    if (!source.includes(STYLE_ID)) source = source.replace('</head>', `${style()}\
</head>`);
    if (!source.includes(SCRIPT_ID)) source = source.replace('</head>', `${script()}\
</head>`);
    return source;
}

module.exports = { STYLE_ID, SCRIPT_ID, inject, script, style };
