const COURSE_INTERACTION_STYLE_ID = 'quizmoto-course-interactions-v3';
const COURSE_INTERACTION_SCRIPT_ID = 'quizmoto-course-interactions-script-v3';

function courseInteractionStyle() {
    return `<style id="${COURSE_INTERACTION_STYLE_ID}">
.qmx-cards{perspective:1200px}.qmx-cards.qmx-flip-grid{grid-template-columns:repeat(2,minmax(240px,320px))!important;gap:16px!important;max-width:664px;align-items:stretch;justify-content:start}
.qmx-card.qmx-flip-card{min-height:0!important;padding:0!important;border:0!important;background:transparent!important;cursor:pointer;outline:none;perspective:1200px;align-self:stretch}.qmx-flip-inner{position:relative;display:grid;width:100%;min-height:220px;transform-style:preserve-3d;transition:transform .55s cubic-bezier(.2,.72,.22,1)}.qmx-flip-card.is-flipped .qmx-flip-inner{transform:rotateY(180deg)}.qmx-flip-face{position:relative;grid-area:1/1;min-height:220px;display:flex;flex-direction:column;justify-content:flex-start;gap:10px;padding:20px 22px;border:1px solid var(--paper-3);border-radius:14px;background:var(--surface);backface-visibility:hidden;-webkit-backface-visibility:hidden;box-shadow:0 7px 18px rgba(15,23,42,.055);overflow:hidden}.qmx-flip-back{transform:rotateY(180deg);border-color:var(--accent)}.qmx-flip-number,.qmx-interaction-index{display:inline-flex;align-items:center;justify-content:center;flex:0 0 30px;width:30px;height:30px;border-radius:8px;background:var(--soft);color:var(--primary-dark);font-size:11px;line-height:1;font-weight:700}.qmx-flip-face .qmx-flip-number{align-self:center}.qmx-flip-title{margin-top:4px;color:var(--ink);font-size:17px;line-height:1.28;font-weight:600}.qmx-flip-hint{margin-top:auto;padding-top:6px;color:var(--primary-dark);font-size:9.5px;line-height:1.2;font-weight:600;letter-spacing:.075em;text-transform:uppercase}.qmx-flip-back p{margin:4px 0 0!important;color:var(--ink-soft)!important;font-size:14px!important;line-height:1.55!important;font-weight:500!important}.qmx-flip-back p strong{color:var(--ink)!important;font-weight:700!important}.qmx-flip-card:hover .qmx-flip-face,.qmx-flip-card:focus-visible .qmx-flip-face{border-color:var(--accent);box-shadow:0 9px 22px rgba(15,23,42,.085)}.qmx-flip-card:focus-visible .qmx-flip-face{outline:2px solid var(--primary);outline-offset:2px}
.qmx-v7-runtime{width:100%;margin-top:18px}.qmx-runtime-prompt{margin:0 0 12px;color:var(--ink-soft);font-size:11px;font-weight:650}.qmx-runtime-tabs{border:1px solid var(--paper-3);border-radius:16px;overflow:hidden;background:var(--surface)}.qmx-runtime-tablist{display:flex;gap:0;overflow:auto;border-bottom:1px solid var(--paper-3);background:var(--soft)}.qmx-runtime-tab{min-width:120px;padding:13px 14px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--ink-soft);font-size:11px;font-weight:750;cursor:pointer}.qmx-runtime-tab[aria-selected="true"]{background:var(--surface);border-bottom-color:var(--accent);color:var(--primary-dark)}.qmx-runtime-tab:focus-visible{outline:2px solid var(--primary);outline-offset:-2px}.qmx-runtime-panel{min-height:240px;padding:24px;display:grid;grid-template-columns:36px 1fr;gap:14px;align-items:start}.qmx-runtime-panel h4{margin:1px 0 8px;color:var(--ink);font-size:16px}.qmx-runtime-panel p{margin:0;color:var(--ink-soft);font-size:14px;line-height:1.62}.qmx-runtime-panel p strong{color:var(--ink);font-weight:700}
.qmx-runtime-accordion{display:grid;gap:10px}.qmx-runtime-accordion-item{border:1px solid var(--paper-3);border-radius:13px;background:var(--surface);overflow:hidden}.qmx-runtime-accordion-item.is-open{border-color:var(--accent)}.qmx-runtime-accordion-button{width:100%;padding:14px 16px;display:flex;align-items:center;justify-content:space-between;gap:12px;border:0;background:transparent;color:var(--ink);font-size:12.5px;font-weight:700;text-align:left;cursor:pointer}.qmx-runtime-accordion-button:focus-visible{outline:2px solid var(--primary);outline-offset:-2px}.qmx-runtime-accordion-copy{padding:2px 16px 16px 16px;color:var(--ink-soft);font-size:13.5px;line-height:1.62}.qmx-runtime-accordion-copy p{margin:0}.qmx-runtime-accordion-copy strong{color:var(--ink);font-weight:700}
.qmx-runtime-process{position:relative;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding-top:4px}.qmx-runtime-process[data-qmx-steps="2"]{grid-template-columns:repeat(2,minmax(0,1fr))}.qmx-runtime-process[data-qmx-steps="3"]{grid-template-columns:repeat(3,minmax(0,1fr))}.qmx-runtime-process:before{content:"";position:absolute;left:8%;right:8%;top:21px;height:2px;background:var(--paper-3)}.qmx-runtime-step{position:relative;z-index:1;padding:0 4px 10px;border:0;background:transparent;color:var(--ink-soft);cursor:pointer;text-align:center}.qmx-runtime-step span{width:36px;height:36px;margin:0 auto 8px;display:grid;place-items:center;border-radius:50%;background:var(--surface);border:2px solid var(--paper-3);font-size:11px;font-weight:800}.qmx-runtime-step strong{display:block;font-size:10px;line-height:1.25}.qmx-runtime-step[aria-selected="true"] span{border-color:var(--accent);background:var(--soft);color:var(--primary-dark)}.qmx-runtime-step-copy{grid-column:1/-1;min-height:132px;padding:18px 20px;border:1px solid var(--paper-3);border-radius:13px;background:var(--surface)}.qmx-runtime-step-copy strong{font-size:12.5px;color:var(--ink)}.qmx-runtime-step-copy p{margin:6px 0 0;color:var(--ink-soft);font-size:13.5px;line-height:1.62}.qmx-runtime-step-copy p strong{font-weight:700}
.qmx-runtime-scenario{display:grid;gap:12px}.qmx-runtime-scenario-context{min-height:88px;padding:16px 18px;border:1px solid var(--paper-3);border-radius:13px;background:var(--surface);color:var(--ink-soft);font-size:13.5px;line-height:1.6}.qmx-runtime-choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.qmx-runtime-choice{min-height:64px;padding:13px 14px;border:1px solid var(--paper-3);border-radius:12px;background:var(--surface);color:var(--ink);font-size:11.5px;font-weight:700;text-align:left;cursor:pointer;display:flex;align-items:center}.qmx-runtime-choice:hover,.qmx-runtime-choice:focus-visible{border-color:var(--accent);outline:none}.qmx-runtime-choice.is-selected{background:var(--soft);border-color:var(--accent);color:var(--primary-dark)}.qmx-runtime-feedback{padding:12px 14px;border:1px solid var(--accent);border-radius:12px;background:var(--soft);color:var(--ink-soft);font-size:12px;line-height:1.5}
.qmx-runtime-progress{margin-top:10px;color:var(--ink-soft);font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}#next-btn[data-qmx-reveal-locked="true"]{opacity:.38!important;cursor:not-allowed!important}
.qmx-learning-shell.no-image{width:min(1680px,94vw)!important;margin-inline:auto!important}.qmx-learning-shell.no-image .qmx-copy{width:100%;display:grid;grid-template-columns:minmax(0,1fr) minmax(460px,1fr);column-gap:52px;row-gap:0;align-items:start;text-align:left}.qmx-learning-shell.no-image .qmx-copy>.eyebrow,.qmx-learning-shell.no-image .qmx-copy>h2,.qmx-learning-shell.no-image .qmx-copy>p{grid-column:1}.qmx-learning-shell.no-image .qmx-copy>.eyebrow{grid-row:1}.qmx-learning-shell.no-image .qmx-copy>h2{grid-row:2;max-width:none;margin-left:0!important;margin-right:0!important}.qmx-learning-shell.no-image .qmx-copy>p{grid-row:3;max-width:none!important;margin-left:0!important;margin-right:0!important}.qmx-learning-shell.no-image .qmx-v7-runtime,.qmx-learning-shell.no-image .qmx-cards,.qmx-learning-shell.no-image .qmx-process,.qmx-learning-shell.no-image .qmx-compare{grid-column:2;grid-row:1/span 3;align-self:center;justify-self:end;width:100%;margin:0!important}
.slide[data-qmx-template="interactive_tabs"] .qmx-learning-shell.no-image .qmx-copy,.slide[data-qmx-template="accordion"] .qmx-learning-shell.no-image .qmx-copy{grid-template-columns:minmax(340px,.82fr) minmax(520px,1.18fr)}.slide[data-qmx-template="process_tabs"] .qmx-learning-shell.no-image .qmx-copy,.slide[data-qmx-template="interactive_timeline"] .qmx-learning-shell.no-image .qmx-copy{grid-template-columns:minmax(320px,.72fr) minmax(560px,1.28fr)}.slide[data-qmx-template="scenario_decision"] .qmx-learning-shell.no-image .qmx-copy{grid-template-columns:minmax(360px,.9fr) minmax(500px,1.1fr)}
@media(max-width:1180px){.qmx-learning-shell.no-image{width:min(980px,96vw)!important}}
@media(max-width:980px){.qmx-learning-shell.no-image .qmx-copy{display:block;text-align:left}.qmx-learning-shell.no-image .qmx-v7-runtime,.qmx-learning-shell.no-image .qmx-cards,.qmx-learning-shell.no-image .qmx-process,.qmx-learning-shell.no-image .qmx-compare{width:100%;max-width:620px;margin-top:22px!important;justify-self:start}}
@media(max-width:760px){.qmx-cards.qmx-flip-grid{grid-template-columns:minmax(0,1fr)!important;max-width:460px}.qmx-runtime-process{grid-template-columns:repeat(2,minmax(0,1fr))!important}.qmx-runtime-process:before{display:none}.qmx-runtime-choice-grid{grid-template-columns:1fr}.qmx-runtime-tablist{display:grid;grid-template-columns:1fr}.qmx-runtime-tab{min-width:0;text-align:left;border-bottom:1px solid var(--paper-3);border-left:3px solid transparent}.qmx-runtime-tab[aria-selected="true"]{border-left-color:var(--accent);border-bottom-color:var(--paper-3)}}
@media(max-width:620px){.qmx-flip-inner,.qmx-flip-face{min-height:190px}.qmx-flip-face{padding:16px 17px}.qmx-runtime-panel{padding:18px;min-height:200px}}
@media(prefers-reduced-motion:reduce){.qmx-flip-inner{transition:none!important}}
</style>`;
}

function courseInteractionScript() {
    return `<script id="${COURSE_INTERACTION_SCRIPT_ID}">
(function(){
  function clean(value){return String(value||'').replace(/\\s+/g,' ').trim()}
  function node(tag,className,text){var el=document.createElement(tag);if(className)el.className=className;if(text!==undefined&&text!==null)el.textContent=text;return el}
  function escapeHtml(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
  function richHtml(value){return escapeHtml(value).replace(/\\*\\*(.+?)\\*\\*/g,'<strong>$1</strong>')}
  function richNode(tag,className,text){var el=document.createElement(tag);if(className)el.className=className;el.innerHTML=richHtml(text);return el}
  function points(slide){return Array.isArray(slide&&slide.keyPoints)?slide.keyPoints.map(clean).filter(Boolean).slice(0,6):[]}
  function sentenceList(value){return clean(value).split(/(?<=[.!?])\\s+/).map(clean).filter(function(item){return item.length>18})}
  function detailFor(s,index,point){var body=sentenceList((s&&s.content)||(s&&s.introText)||'');var candidate=body[index];if(candidate&&candidate.toLowerCase().indexOf(String(point||'').toLowerCase().slice(0,12))===-1)return candidate;if(body.length)return body[index%body.length];return point||''}
  function learningSlides(){return Array.prototype.slice.call(document.querySelectorAll('.slide[data-kind="learning"]'))}
  function dataSlides(data){var source=data||window.__quizmotoData||{};return Array.isArray(source.slides)?source.slides:[]}
  function loadCourseData(done){var embedded=window.__quizmotoData||{};if(Array.isArray(embedded.slides)&&embedded.slides.length){done(embedded);return}if(typeof window.fetch!=='function'){done(embedded);return}window.fetch('content.json',{cache:'no-store'}).then(function(response){if(!response.ok)throw new Error('content.json '+response.status);return response.json()}).then(function(payload){if(payload&&typeof payload==='object')window.__quizmotoData=payload;done(payload||embedded)}).catch(function(){done(embedded)})}
  function existingTarget(slide){return slide.querySelector('.qmx-cards,.qmx-process,.qmx-timeline,.qmx-compare,.qmx-hub-list,.hub-list,.qmx-hub,.qmx-cycle,.qmx-matrix')}
  function secondaryHost(slide){var el=slide.querySelector('.qmx-v7-secondary');return el&&!el.childNodes.length?el:null}
  function templateFor(s){var explicit=clean(s&&s.interaction&&s.interaction.templateId);return explicit||'flip_cards_classic'}
  function promptFor(s,fallback){return clean(s&&s.interaction&&s.interaction.prompt)||fallback}
  function makeRuntime(slide,template){var old=existingTarget(slide);if(!old)return null;var host=node('div','qmx-v7-runtime');host.setAttribute('data-qmx-template',template);old.parentNode.replaceChild(host,old);return host}
  function markVisited(control){control.setAttribute('data-qmx-visited','true')}
  function progress(host,total,extra){var seen=host.querySelectorAll('[data-qmx-required="true"][data-qmx-visited="true"]').length;if(extra)seen+=extra.querySelectorAll('[data-qmx-required="true"][data-qmx-visited="true"]').length;var out=host.querySelector('.qmx-runtime-progress');if(out)out.textContent=seen+' / '+total+' explored';host.setAttribute('data-qmx-complete',seen>=total?'true':'false');syncNextGate()}
  function addPrompt(host,text){if(!text)return;var prompt=node('p','qmx-runtime-prompt',text);if(host.parentNode)host.parentNode.insertBefore(prompt,host);else host.appendChild(prompt)}

  function buildTabs(slide,s,template){var list=points(s);if(list.length<2)return false;var host=makeRuntime(slide,template);if(!host)return false;addPrompt(host,promptFor(s,'Explore each point before continuing.'));var shell=node('div','qmx-runtime-tabs');var tabs=node('div','qmx-runtime-tablist');tabs.setAttribute('role','tablist');var panel=node('div','qmx-runtime-panel');panel.setAttribute('role','tabpanel');host.appendChild(shell);shell.appendChild(tabs);shell.appendChild(panel);host.appendChild(node('div','qmx-runtime-progress','0 / '+list.length+' explored'));
    function show(index){var buttons=tabs.querySelectorAll('.qmx-runtime-tab');Array.prototype.forEach.call(buttons,function(btn,i){btn.setAttribute('aria-selected',i===index?'true':'false');btn.tabIndex=i===index?0:-1});panel.textContent='';panel.appendChild(node('span','qmx-interaction-index',String(index+1).padStart(2,'0')));var wrap=node('div');wrap.appendChild(richNode('h4','',list[index]));wrap.appendChild(richNode('p','',detailFor(s,index,list[index])));panel.appendChild(wrap);markVisited(buttons[index]);progress(host,list.length)}
    list.forEach(function(item,index){var btn=node('button','qmx-runtime-tab','Point '+String(index+1).padStart(2,'0'));btn.type='button';btn.setAttribute('role','tab');btn.setAttribute('data-qmx-required','true');btn.addEventListener('click',function(){show(index)});btn.addEventListener('keydown',function(e){if(e.key!=='ArrowRight'&&e.key!=='ArrowLeft')return;e.preventDefault();var next=(index+(e.key==='ArrowRight'?1:-1)+list.length)%list.length;tabs.querySelectorAll('.qmx-runtime-tab')[next].focus();show(next)});tabs.appendChild(btn)});show(0);return true}

  function buildAccordion(slide,s){var list=points(s);if(list.length<2)return false;var host=makeRuntime(slide,'accordion');if(!host)return false;addPrompt(host,promptFor(s,'Open each section to reveal the practical detail.'));var shell=node('div','qmx-runtime-accordion');host.appendChild(shell);host.appendChild(node('div','qmx-runtime-progress','0 / '+list.length+' explored'));
    var secondary=secondaryHost(slide);var secondaryShell=null;if(secondary){secondaryShell=node('div','qmx-runtime-accordion');secondary.appendChild(secondaryShell)}var splitAt=secondaryShell?Math.ceil(list.length/2):list.length;
    var entries=[];list.forEach(function(item,index){var row=node('div','qmx-runtime-accordion-item');var btn=node('button','qmx-runtime-accordion-button');btn.type='button';btn.setAttribute('aria-expanded','false');btn.setAttribute('data-qmx-required','true');btn.appendChild(richNode('span','',String(index+1).padStart(2,'0')+'  '+item));btn.appendChild(node('span','qmx-accordion-sign','+'));var copy=node('div','qmx-runtime-accordion-copy');copy.appendChild(richNode('p','',detailFor(s,index,item)));copy.hidden=true;row.appendChild(btn);row.appendChild(copy);(index<splitAt?shell:secondaryShell).appendChild(row);entries.push({row:row,btn:btn,copy:copy})});
    entries.forEach(function(entry){entry.btn.addEventListener('click',function(){var open=entry.copy.hidden;entries.forEach(function(other){var willOpen=other===entry&&open;other.copy.hidden=!willOpen;other.row.classList.toggle('is-open',willOpen);other.btn.setAttribute('aria-expanded',willOpen?'true':'false');other.btn.querySelector('.qmx-accordion-sign').textContent=willOpen?'−':'+'});if(open)markVisited(entry.btn);progress(host,list.length,secondary)})});
    progress(host,list.length,secondary);return true}

  function buildProcess(slide,s,template){var list=points(s);var total=Math.min(list.length,4);if(total<2)return false;var host=makeRuntime(slide,template);if(!host)return false;addPrompt(host,promptFor(s,'Explore every stage to understand the sequence.'));var shell=node('div','qmx-runtime-process');shell.setAttribute('data-qmx-steps',String(total));var copy=node('div','qmx-runtime-step-copy');host.appendChild(shell);host.appendChild(node('div','qmx-runtime-progress','0 / '+total+' explored'));
    function show(index){var buttons=shell.querySelectorAll('.qmx-runtime-step');Array.prototype.forEach.call(buttons,function(btn,i){btn.setAttribute('aria-selected',i===index?'true':'false')});copy.textContent='';copy.appendChild(richNode('strong','',(template==='interactive_timeline'?'Milestone '+(index+1)+' — ':'Step '+(index+1)+' — ')+list[index]));copy.appendChild(richNode('p','',detailFor(s,index,list[index])));markVisited(buttons[index]);progress(host,total)}
    list.slice(0,total).forEach(function(item,index){var btn=node('button','qmx-runtime-step');btn.type='button';btn.setAttribute('data-qmx-required','true');btn.appendChild(node('span','',String(index+1)));btn.appendChild(node('strong','',template==='interactive_timeline'?'Milestone':'Step'));btn.addEventListener('click',function(){show(index)});shell.appendChild(btn)});shell.appendChild(copy);show(0);return true}

  function buildScenario(slide,s){var list=points(s);if(list.length<2)return false;var host=makeRuntime(slide,'scenario_decision');if(!host)return false;addPrompt(host,promptFor(s,'Choose the response you would take.'));var shell=node('div','qmx-runtime-scenario');var context=richNode('div','qmx-runtime-scenario-context',clean(s&&s.revealText)||clean(s&&s.introText)||clean(s&&s.content)||'Consider the situation before choosing.');var choices=node('div','qmx-runtime-choice-grid');var feedback=node('div','qmx-runtime-feedback');feedback.hidden=true;shell.appendChild(context);shell.appendChild(choices);shell.appendChild(feedback);host.appendChild(shell);host.appendChild(node('div','qmx-runtime-progress','Choose one response to continue'));
    var secondary=secondaryHost(slide);var secondaryChoices=null;if(secondary){secondaryChoices=node('div','qmx-runtime-choice-grid');secondary.appendChild(secondaryChoices)}
    var items=list.slice(0,4);var splitAt=secondaryChoices?Math.ceil(items.length/2):items.length;var buttons=[];
    items.forEach(function(item,index){var btn=node('button','qmx-runtime-choice',item);btn.type='button';buttons.push(btn);btn.addEventListener('click',function(){buttons.forEach(function(other){other.classList.remove('is-selected')});btn.classList.add('is-selected');host.setAttribute('data-qmx-complete','true');feedback.hidden=false;feedback.textContent='Decision recorded. Compare your reasoning with the course guidance before continuing.';var out=host.querySelector('.qmx-runtime-progress');if(out)out.textContent='Decision completed';syncNextGate()});(index<splitAt?choices:secondaryChoices).appendChild(btn)});host.setAttribute('data-qmx-complete','false');syncNextGate();return true}

  function upgradeCard(card,index,s){if(!card||card.getAttribute('data-qmx-flip-ready')==='true')return;var numberNode=card.querySelector('span');var copyNode=card.querySelector('p');var number=clean(numberNode&&numberNode.textContent)||String(index+1).padStart(2,'0');var copy=clean(copyNode&&copyNode.textContent);if(!copy)return;var detail=detailFor(s,index,copy);card.textContent='';card.classList.add('qmx-flip-card');card.setAttribute('data-qmx-flip-ready','true');card.setAttribute('data-qmx-revealed','false');card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-expanded','false');card.setAttribute('aria-label','Reveal: '+copy);var inner=node('div','qmx-flip-inner');var front=node('div','qmx-flip-face qmx-flip-front');var back=node('div','qmx-flip-face qmx-flip-back');front.appendChild(node('span','qmx-flip-number',number));front.appendChild(richNode('div','qmx-flip-title',copy));front.appendChild(node('div','qmx-flip-hint','Click to reveal'));back.appendChild(node('span','qmx-flip-number',number));back.appendChild(richNode('p','',detail));back.appendChild(node('div','qmx-flip-hint','Click to flip back'));inner.appendChild(front);inner.appendChild(back);card.appendChild(inner)}
  function upgradeFlipCards(slide,s){Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards'),function(grid){var cards=grid.querySelectorAll('.qmx-card');if(!cards.length)return;if(!grid.classList.contains('qmx-flip-grid'))grid.classList.add('qmx-flip-grid');Array.prototype.forEach.call(cards,function(card,index){upgradeCard(card,index,s)})})}
  function activeSlide(){return document.querySelector('.slide.active')}
  function unrevealedCards(slide){if(!slide)return[];return Array.prototype.filter.call(slide.querySelectorAll('.qmx-flip-card'),function(card){return card.getAttribute('data-qmx-revealed')!=='true'})}
  function runtimeIncomplete(slide){if(!slide)return false;var runtime=slide.querySelector('.qmx-v7-runtime');return !!runtime&&runtime.getAttribute('data-qmx-complete')==='false'}
  function syncNextGate(){var next=document.getElementById('next-btn');if(!next)return;var slide=activeSlide();var locked=unrevealedCards(slide).length>0||runtimeIncomplete(slide);if(locked){next.disabled=true;next.setAttribute('data-qmx-reveal-locked','true');next.title='Complete the interaction before continuing';next.setAttribute('aria-label','Complete the interaction before continuing')}else{if(next.getAttribute('data-qmx-reveal-locked')==='true')next.disabled=false;next.removeAttribute('data-qmx-reveal-locked');next.removeAttribute('title');next.removeAttribute('aria-label')}}
  function toggleCard(card){if(!card)return;var flipped=!card.classList.contains('is-flipped');card.classList.toggle('is-flipped',flipped);if(flipped)card.setAttribute('data-qmx-revealed','true');card.setAttribute('aria-expanded',flipped?'true':'false');card.setAttribute('aria-label',(flipped?'Hide':'Reveal')+' key point');syncNextGate()}
  document.addEventListener('click',function(event){var card=event.target&&event.target.closest?event.target.closest('.qmx-flip-card'):null;if(card)toggleCard(card)},false)
  document.addEventListener('keydown',function(event){var card=event.target&&event.target.closest?event.target.closest('.qmx-flip-card'):null;if(!card||(event.key!=='Enter'&&event.key!==' '))return;event.preventDefault();toggleCard(card)},false)
  document.addEventListener('click',function(event){var next=event.target&&event.target.closest?event.target.closest('#next-btn'):null;if(!next)return;var slide=activeSlide();if(!unrevealedCards(slide).length&&!runtimeIncomplete(slide))return;event.preventDefault();event.stopImmediatePropagation();syncNextGate()},true)
  document.addEventListener('click',function(event){var nav=event.target&&event.target.closest?event.target.closest('#next-btn,#prev-btn'):null;if(nav)setTimeout(syncNextGate,0)},false)
  function installWithData(courseData){var nodes=learningSlides();var data=dataSlides(courseData);nodes.forEach(function(slide,index){var s=data[index]||{};var template=templateFor(s);slide.setAttribute('data-qmx-template',template);var built=false;if(template==='interactive_tabs'||template==='labelled_graphic'||template==='hotspot_explorer')built=buildTabs(slide,s,template);else if(template==='accordion')built=buildAccordion(slide,s);else if(template==='process_tabs'||template==='interactive_timeline'||template==='sequence_builder')built=buildProcess(slide,s,template);else if(template==='scenario_decision'||template==='branching_scenario'||template==='advanced_knowledge_check'||template==='sorting_activity')built=buildScenario(slide,s);if(!built)upgradeFlipCards(slide,s)});syncNextGate();window.addEventListener('load',function(){setTimeout(syncNextGate,0)})}
  function install(){loadCourseData(installWithData)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
</script>`;
}

function injectCourseInteractionsUi(html) {
    let source = String(html || '');
    if (!source) return source;

    if (!source.includes(COURSE_INTERACTION_STYLE_ID)) {
        const style = courseInteractionStyle();
        source = source.includes('</head>') ? source.replace('</head>', `${style}\n</head>`) : `${style}\n${source}`;
    }

    if (!source.includes(COURSE_INTERACTION_SCRIPT_ID)) {
        const script = courseInteractionScript();
        source = source.includes('</body>') ? source.replace('</body>', `${script}\n</body>`) : `${source}\n${script}`;
    }

    return source;
}

module.exports = {
    COURSE_INTERACTION_STYLE_ID,
    COURSE_INTERACTION_SCRIPT_ID,
    courseInteractionStyle,
    courseInteractionScript,
    injectCourseInteractionsUi
};
