'use strict';

const JSZip = require('jszip');

const STYLE_ID = 'quizmoto-scenario-learning-runtime-v1';
const SCRIPT_ID = 'quizmoto-scenario-learning-runtime-script-v1';

function safeAttr(value) {
    return String(value || '').replace(/[^a-z0-9_.-]/gi, '').slice(0, 120);
}

function style() {
    return `<style id="${STYLE_ID}">
.qmx-scenario-body{display:flex;flex:1 1 auto;min-width:0;min-height:0;overflow:hidden;position:relative}
.qmx-scenario-main{flex:1 1 auto;min-width:0;min-height:0;position:relative}
.qmx-scenario-sidebar{display:none}
body[data-qmx-course-template="scenario-learning"] main{overflow:hidden!important}
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"].active{align-items:center!important;justify-content:center!important;padding:14px 26px!important}
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-cover-shell,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-learning-shell,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-quiz-shell,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-final-shell{width:min(1320px,100%)!important;height:100%!important;max-width:none!important;min-height:0!important;margin:auto!important;box-sizing:border-box!important}
body[data-qmx-course-template="scenario-learning"] .qmx-learning-shell{gap:38px!important;align-items:stretch!important}
body[data-qmx-course-template="scenario-learning"] .qmx-learning-shell.has-image{grid-template-columns:minmax(0,1.05fr) minmax(360px,.95fr)!important}
body[data-qmx-course-template="scenario-learning"] .qmx-learning-shell.no-image{grid-template-columns:1fr!important}
body[data-qmx-course-template="scenario-learning"] .qmx-learning-shell .qmx-copy{min-width:0;min-height:0;display:flex!important;flex-direction:column!important;justify-content:center!important;padding:clamp(14px,2.2vh,26px) 0!important}
body[data-qmx-course-template="scenario-learning"] .qmx-copy .eyebrow{display:inline-flex;align-items:center;width:max-content;max-width:100%;min-height:24px;padding:5px 9px;border:1px solid var(--paper-3,#d8e5e2);border-radius:999px;background:var(--soft,#edf8f6);color:var(--primary-dark,#087f75);font-size:9px!important;font-weight:800!important;letter-spacing:.09em!important}
body[data-qmx-course-template="scenario-learning"] .qmx-copy h2{font-size:clamp(34px,3.35vw,50px)!important;line-height:1.02!important;max-width:850px!important;margin-top:12px!important}
body[data-qmx-course-template="scenario-learning"] .qmx-copy>p{font-size:15.5px!important;line-height:1.52!important;max-width:800px!important}
body[data-qmx-course-template="scenario-learning"] .qmx-native-media{align-self:center!important;width:100%!important;height:min(78%,520px)!important;min-height:310px!important;aspect-ratio:auto!important;border-radius:24px!important;overflow:hidden!important;box-shadow:0 20px 52px rgba(15,35,32,.12)}
body[data-qmx-course-template="scenario-learning"] .qmx-native-media img{width:100%!important;height:100%!important;object-fit:cover!important}
body[data-qmx-course-template="scenario-learning"] footer{height:78px!important;min-height:78px!important;padding:12px 28px 14px!important;align-items:center!important}
body[data-qmx-course-template="scenario-learning"] footer .nav-btn{min-height:46px!important;padding:11px 20px!important}
body[data-qmx-course-template="scenario-learning"] #next-btn[data-qmx-scenario-locked="true"]{visibility:hidden!important;pointer-events:none!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-source{display:none!important;visibility:hidden!important;pointer-events:none!important;height:0!important;min-height:0!important;margin:0!important;padding:0!important;overflow:hidden!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px;width:100%;margin-top:18px}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-option{display:grid;grid-template-columns:38px minmax(0,1fr);grid-template-rows:auto auto;column-gap:12px;row-gap:4px;align-items:center;min-height:86px;padding:13px 15px;border:1px solid var(--paper-3,#d8e5e2);border-radius:15px;background:var(--surface,#fff);color:var(--ink,#10211f);text-align:left;cursor:pointer;box-shadow:0 8px 24px rgba(15,35,32,.035);transition:border-color .18s ease,background .18s ease,transform .18s ease,box-shadow .18s ease}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-option:hover,
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-option:focus-visible{border-color:var(--primary,#119286);outline:none;box-shadow:0 12px 28px rgba(17,146,134,.10)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-option.is-selected{border-color:var(--primary,#119286);background:var(--soft,#edf8f6);transform:translateY(-1px)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-option.is-visited .qmx-scenario-number{border-color:var(--primary,#119286);background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-number{grid-row:1/span 2;display:grid;place-items:center;width:36px;height:36px;border:1px solid var(--paper-3,#d8e5e2);border-radius:11px;background:var(--paper,#f3f8f7);color:var(--primary-dark,#087f75);font-size:10px;font-weight:800}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-label{min-width:0;font-size:14px;line-height:1.28;font-weight:720;color:var(--ink,#10211f);display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-hint{font-size:8.5px;line-height:1.2;text-transform:uppercase;letter-spacing:.08em;font-weight:800;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-panel{position:relative;margin-top:13px;padding:16px 18px 17px 20px;border:1px solid var(--paper-3,#d8e5e2);border-left:4px solid var(--primary,#119286);border-radius:15px;background:linear-gradient(135deg,var(--surface,#fff),var(--soft,#edf8f6))}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-panel[hidden]{display:none!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-panel-kicker{font-size:9px;line-height:1.2;text-transform:uppercase;letter-spacing:.1em;font-weight:850;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-panel p{margin:7px 0 0!important;font-size:13.8px!important;line-height:1.46!important;font-weight:550!important;color:var(--ink,#10211f)!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-instruction{display:flex;align-items:center;gap:8px;margin-top:12px;font-size:11px;line-height:1.35;font-weight:680;color:var(--ink-soft,#49625e)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-instruction::before{content:'→';display:grid;place-items:center;width:22px;height:22px;flex:0 0 22px;border-radius:50%;background:var(--soft,#edf8f6);color:var(--primary-dark,#087f75);font-size:10px;font-weight:850}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-instruction.is-complete{color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-instruction.is-complete::before{content:'✓';background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-reveal{display:inline-flex;align-items:center;justify-content:center;align-self:flex-start;min-height:48px;margin:20px 0 0;padding:12px 22px;border:1px solid var(--primary,#119286);border-radius:999px;background:var(--primary,#119286);color:#fff;font-size:13px;font-weight:750;cursor:pointer}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-reveal:hover{filter:brightness(.96)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-choice-banner{display:flex;align-items:center;gap:10px;margin-top:16px;padding:11px 14px;border-radius:13px;background:var(--paper,#f3f8f7);font-size:11px;line-height:1.35;color:var(--ink-soft,#49625e)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-choice-banner strong{color:var(--ink,#10211f)}
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-interaction="focus_reveal"] .qmx-cards,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-interaction="focus_reveal"] .qmx-static-cards{display:none!important}
body[data-qmx-course-template="scenario-learning"] .qmx-quiz-shell{display:flex!important;flex-direction:column!important;justify-content:center!important;padding:clamp(34px,5vh,62px) clamp(38px,5vw,72px)!important;border:1px solid var(--paper-3,#d8e5e2);border-radius:24px;background:var(--surface,#fff)}
body[data-qmx-course-template="scenario-learning"] .qmx-final-shell{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;padding:clamp(36px,5vh,66px)!important;border:1px solid var(--paper-3,#d8e5e2);border-radius:24px;background:var(--surface,#fff);text-align:center}
@media(min-width:1500px){
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar{display:flex;flex:0 0 238px;width:238px;min-width:238px;min-height:0;flex-direction:column;border-right:1px solid var(--paper-3,#d8e5e2);background:linear-gradient(180deg,var(--surface,#fff) 0%,var(--paper,#f3f8f7) 100%);z-index:12;overflow:hidden}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar-head{padding:19px 17px 15px;border-bottom:1px solid var(--paper-3,#d8e5e2)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar-kicker{font-size:9px;text-transform:uppercase;letter-spacing:.11em;font-weight:850;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar-title{margin-top:8px;font-size:14px;line-height:1.28;font-weight:750;color:var(--ink,#10211f);display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar-progress{display:flex;justify-content:space-between;gap:10px;margin-top:12px;font-size:10px;color:var(--ink-soft,#49625e)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar-progress strong{color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-sidebar-list{flex:1 1 auto;min-height:0;width:100%;overflow-y:auto;overflow-x:hidden;padding:12px 10px 16px;scrollbar-width:thin;scrollbar-color:rgba(17,109,99,.24) transparent}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-item{width:100%;min-width:0;box-sizing:border-box;display:grid;grid-template-columns:30px minmax(0,1fr) 16px;align-items:center;gap:8px;margin:3px 0;padding:9px 8px;border:0;border-radius:11px;background:transparent;color:var(--ink-soft,#49625e);text-align:left;overflow:hidden;cursor:default}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-item.is-visited{cursor:pointer;color:var(--ink,#10211f)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-item.is-visited:hover{background:rgba(17,146,134,.07)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-item.is-active{background:var(--soft,#edf8f6);color:var(--ink,#10211f);box-shadow:inset 3px 0 0 var(--primary,#119286)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-number{display:grid;place-items:center;width:28px;height:28px;border:1px solid var(--paper-3,#d8e5e2);border-radius:9px;background:var(--surface,#fff);font-size:9px;font-weight:850;color:var(--primary-dark,#087f75)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-item.is-active .qmx-scenario-nav-number{border-color:var(--primary,#119286);background:var(--primary,#119286);color:#fff}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-copy{min-width:0;overflow:hidden}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-type{display:block;font-size:8px;line-height:1.1;text-transform:uppercase;letter-spacing:.07em;font-weight:800;color:var(--primary-dark,#087f75);opacity:.72;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-label{display:-webkit-box;margin-top:3px;font-size:10.8px;line-height:1.28;font-weight:640;white-space:normal;overflow:hidden;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow-wrap:anywhere}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-state{display:grid;place-items:center;font-size:11px;font-weight:850;color:var(--primary,#119286)}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-nav-item:not(.is-visited):not(.is-active){opacity:.56}
body[data-qmx-course-template="scenario-learning"] .qmx-copy h2{font-size:clamp(38px,3.15vw,55px)!important;max-width:900px!important}
body[data-qmx-course-template="scenario-learning"] .qmx-copy>p{font-size:16px!important;line-height:1.54!important;max-width:830px!important}
}
@media(max-width:980px){
body[data-qmx-course-template="scenario-learning"] .qmx-learning-shell.has-image{grid-template-columns:minmax(0,1fr) minmax(290px,.78fr)!important;gap:25px!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
}
@media(max-width:760px){
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"].active{padding:12px!important}
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-cover-shell,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-learning-shell,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-quiz-shell,
body[data-qmx-course-template="scenario-learning"] .slide[data-qmx-template-stage="true"]>.qmx-final-shell{width:100%!important;height:100%!important}
body[data-qmx-course-template="scenario-learning"] .qmx-learning-shell.has-image{grid-template-columns:1fr!important}
body[data-qmx-course-template="scenario-learning"] .qmx-native-media{display:none!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-grid{grid-template-columns:1fr!important}
}
@media(max-height:720px){
body[data-qmx-course-template="scenario-learning"] footer{height:70px!important;min-height:70px!important;padding:9px 22px 11px!important}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-option{min-height:72px;padding:10px 12px}
body[data-qmx-course-template="scenario-learning"] .qmx-scenario-panel{padding:12px 14px}
}
@media(prefers-reduced-motion:reduce){body[data-qmx-course-template="scenario-learning"] *{transition:none!important}}
</style>`;
}

function script() {
    return `<script id="${SCRIPT_ID}">
(function(){
  var state={maxVisited:0,lastIndex:-1,navigating:false};
  var actionWords=/^(ask|avoid|challenge|check|confirm|contact|do|ensure|escort|follow|hold|never|notify|pause|refuse|report|request|scan|stop|use|verify|wait|allow|call|direct|deny|lock|open|share)\\b/i;
  var stopWords={a:1,an:1,the:1,and:1,or:1,but:1,is:1,are:1,was:1,were:1,be:1,to:1,of:1,for:1,in:1,on:1,with:1,from:1,as:1,at:1,by:1,can:1,could:1,may:1,might:1,will:1,would:1,should:1,this:1,that:1,these:1,those:1,it:1,its:1,they:1,them:1,their:1,you:1,your:1,we:1,our:1};
  function make(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
  function clean(value){return String(value||'').replace(/\\s+/g,' ').trim();}
  function slides(){return Array.prototype.slice.call(document.querySelectorAll('main .slide'));}
  function activeSlide(){return document.querySelector('main .slide.active');}
  function activeIndex(){var list=slides(),active=activeSlide();return Math.max(0,list.indexOf(active));}
  function courseTitle(){var h=document.querySelector('#app>header h1,header h1'),cover=document.querySelector('.slide[data-kind="cover"] h2');return clean((h&&h.textContent)||(cover&&cover.textContent)||'Scenario course');}
  function textOf(node){if(!node)return '';var ps=node.querySelectorAll?node.querySelectorAll('p'):[];if(ps&&ps.length)return Array.prototype.map.call(ps,function(p){return clean(p.textContent);}).filter(Boolean).join(' ');return clean(node.textContent);}
  function sourceCards(slide){return Array.prototype.slice.call(slide.querySelectorAll('.qmx-cards .qmx-card,.qmx-static-cards .qmx-card'));}
  function markSource(node){if(!node)return;node.classList.remove('qmx-cards');node.classList.add('qmx-scenario-source');}
  function shortLabel(value,index){var source=clean(value).replace(/^[0-9]+[.)\\s-]*/,'').replace(/[.!?]+$/,'');if(!source)return 'Point '+String(index+1).padStart(2,'0');var parts=source.split(/[,:;–—]/).map(function(v){return clean(v);}).filter(Boolean);for(var p=0;p<parts.length;p++){var w=parts[p].split(/\\s+/);if(w.length>=2&&w.length<=6&&parts[p].length<=58)return parts[p];}var words=source.split(/\\s+/),picked=[],seen={};for(var i=0;i<words.length&&picked.length<5;i++){var raw=words[i].replace(/[^A-Za-z0-9'-]/g,''),key=raw.toLowerCase();if(!raw||stopWords[key]||seen[key])continue;seen[key]=1;picked.push(raw);}var label=picked.join(' ')||words.slice(0,5).join(' ');return label.charAt(0).toUpperCase()+label.slice(1);}
  function notify(slide){try{slide.dispatchEvent(new CustomEvent('qmx:scenario-update',{bubbles:true}));}catch(e){var ev=document.createEvent('Event');ev.initEvent('qmx:scenario-update',true,true);slide.dispatchEvent(ev);}}
  function instruction(copy,text){var n=make('div','qmx-scenario-instruction',text);copy.appendChild(n);return n;}
  function markComplete(note,text){if(!note)return;note.classList.add('is-complete');note.textContent=text;}
  function panel(copy,kicker,prompt,hidden){var box=make('div','qmx-scenario-panel'),head=make('div','qmx-scenario-panel-kicker',kicker),detail=make('p','',prompt);if(hidden)box.hidden=true;box.appendChild(head);box.appendChild(detail);copy.appendChild(box);return {box:box,head:head,detail:detail};}
  function option(cls,index,label,hint){var b=make('button','qmx-scenario-option '+cls);b.type='button';b.appendChild(make('span','qmx-scenario-number',String(index+1).padStart(2,'0')));b.appendChild(make('span','qmx-scenario-label',label));b.appendChild(make('span','qmx-scenario-hint',hint));return b;}
  function progress(note,count,total,noun){var done=total>0&&count>=total;note.classList.toggle('is-complete',done);note.textContent=done?'All '+noun+' reviewed • Next is unlocked':count+' of '+total+' '+noun+' reviewed • complete all to continue';}
  function cleanupCore(slide){Array.prototype.forEach.call(slide.querySelectorAll('.qmx-explore-grid,.qmx-hotspot-panel,.qmx-template-layer,.qmx-focus-trigger'),function(n){n.remove();});}
  function prepareFocus(slide){if(slide.getAttribute('data-qmx-scenario-owned')==='focus_reveal')return;var copy=slide.querySelector('.qmx-copy'),cards=sourceCards(slide);if(!copy)return;slide.setAttribute('data-qmx-scenario-owned','focus_reveal');cleanupCore(slide);Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards,.qmx-static-cards'),markSource);var details=cards.map(textOf).filter(Boolean),button=make('button','qmx-scenario-reveal','Reveal coach\\'s note');button.type='button';copy.appendChild(button);var coach=panel(copy,'Coach\\'s note',details.length?details.join(' '):'Review the situation and identify the safest behaviour before continuing.',true);var note=instruction(copy,'Reveal the coach\\'s note to continue');button.onclick=function(){coach.box.hidden=false;slide.setAttribute('data-qmx-scenario-focus-complete','true');markComplete(note,'Coach\\'s note reviewed • Next is unlocked');notify(slide);};}
  function prepareSteps(slide){if(slide.getAttribute('data-qmx-scenario-owned')==='step_explore')return;var copy=slide.querySelector('.qmx-copy'),source=slide.querySelector('.qmx-process'),steps=source?Array.prototype.slice.call(source.querySelectorAll('.qmx-step')):[];if(!copy||!source||!steps.length)return;slide.setAttribute('data-qmx-scenario-owned','step_explore');source.classList.add('qmx-scenario-source');var items=steps.map(function(s,i){var d=textOf(s);return {detail:d,label:shortLabel(d,i)};}),grid=make('div','qmx-scenario-grid qmx-scenario-steps');copy.insertBefore(grid,source);var coach=panel(copy,'Guided sequence','Select a step to reveal the coaching detail.',false),note=instruction(copy,'Explore all '+items.length+' steps to continue');function sync(){progress(note,grid.querySelectorAll('[data-qmx-scenario-visited="true"]').length,items.length,'steps');}items.forEach(function(item,i){var b=option('qmx-scenario-step',i,item.label,'Select to explore');b.setAttribute('data-qmx-scenario-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.children,function(x){x.classList.remove('is-selected');});b.classList.add('is-selected','is-visited');b.setAttribute('data-qmx-scenario-visited','true');coach.head.textContent='Step '+String(i+1).padStart(2,'0');coach.detail.textContent=item.detail;sync();notify(slide);};grid.appendChild(b);});sync();}
  function prepareExplore(slide){if(slide.getAttribute('data-qmx-scenario-owned')==='hotspot_explore')return;var copy=slide.querySelector('.qmx-copy'),cards=sourceCards(slide);if(!copy||!cards.length)return;slide.setAttribute('data-qmx-scenario-owned','hotspot_explore');cleanupCore(slide);Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards,.qmx-static-cards'),markSource);var items=cards.slice(0,4).map(function(c,i){var d=textOf(c);return {detail:d,label:shortLabel(d,i)};}),grid=make('div','qmx-scenario-grid qmx-scenario-clues');copy.appendChild(grid);var coach=panel(copy,'What do you notice?','Select each clue to reveal why it matters.',false),note=instruction(copy,'Explore all '+items.length+' clues to continue');function sync(){progress(note,grid.querySelectorAll('[data-qmx-scenario-visited="true"]').length,items.length,'clues');}items.forEach(function(item,i){var b=option('qmx-scenario-clue',i,item.label,'Select to explore');b.setAttribute('data-qmx-scenario-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.children,function(x){x.classList.remove('is-selected');});b.classList.add('is-selected','is-visited');b.setAttribute('data-qmx-scenario-visited','true');coach.head.textContent='Clue '+String(i+1).padStart(2,'0');coach.detail.textContent=item.detail;sync();notify(slide);};grid.appendChild(b);});sync();}
  function prepareRevealCards(slide){if(slide.getAttribute('data-qmx-scenario-owned')==='click_reveal')return;var copy=slide.querySelector('.qmx-copy'),cards=sourceCards(slide),source=slide.querySelector('.qmx-cards,.qmx-static-cards');if(!copy||!cards.length||!source)return;slide.setAttribute('data-qmx-scenario-owned','click_reveal');var items=cards.map(function(c,i){var d=textOf(c);return {detail:d,label:shortLabel(d,i)};});markSource(source);var grid=make('div','qmx-scenario-grid qmx-scenario-reveals');copy.insertBefore(grid,source);var coach=panel(copy,'Learning point','Select a card to reveal the detail.',false),note=instruction(copy,'Reveal all '+items.length+' points to continue');function sync(){progress(note,grid.querySelectorAll('[data-qmx-scenario-visited="true"]').length,items.length,'points');}items.forEach(function(item,i){var b=option('qmx-scenario-reveal-option',i,item.label,'Click to reveal');b.setAttribute('data-qmx-scenario-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.children,function(x){x.classList.remove('is-selected');});b.classList.add('is-selected','is-visited');b.setAttribute('data-qmx-scenario-visited','true');coach.head.textContent='Point '+String(i+1).padStart(2,'0');coach.detail.textContent=item.detail;sync();notify(slide);};grid.appendChild(b);});sync();}
  function prepareCompare(slide){if(slide.getAttribute('data-qmx-scenario-owned')==='compare_reveal')return;var copy=slide.querySelector('.qmx-copy'),source=slide.querySelector('.qmx-compare');if(!copy||!source)return;var pieces=Array.prototype.slice.call(source.querySelectorAll('.qmx-compare-col p'));if(!pieces.length)return;slide.setAttribute('data-qmx-scenario-owned','compare_reveal');source.classList.add('qmx-scenario-source');var items=pieces.slice(0,4).map(function(p,i){var d=clean(p.textContent);return {detail:d,label:shortLabel(d,i)};}),grid=make('div','qmx-scenario-grid qmx-scenario-compare');copy.insertBefore(grid,source);var coach=panel(copy,'Compare outcomes','Select each point to reveal the consequence or distinction.',false),note=instruction(copy,'Review all '+items.length+' comparison points to continue');function sync(){progress(note,grid.querySelectorAll('[data-qmx-scenario-visited="true"]').length,items.length,'comparison points');}items.forEach(function(item,i){var b=option('qmx-scenario-compare-option',i,item.label,'Select to compare');b.setAttribute('data-qmx-scenario-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.children,function(x){x.classList.remove('is-selected');});b.classList.add('is-selected','is-visited');b.setAttribute('data-qmx-scenario-visited','true');coach.head.textContent='Comparison '+String(i+1).padStart(2,'0');coach.detail.textContent=item.detail;sync();notify(slide);};grid.appendChild(b);});sync();}
  function actionable(items){var hits=items.filter(function(item){return actionWords.test(clean(item.label))||/\\b(would|should|best|safest|response|action|choice)\\b/i.test(item.label);}).length;return hits>=2;}
  function prepareDecision(slide){if(slide.getAttribute('data-qmx-scenario-owned')==='decision_explore')return;var copy=slide.querySelector('.qmx-copy'),cards=sourceCards(slide);if(!copy||!cards.length)return;slide.setAttribute('data-qmx-scenario-owned','decision_explore');Array.prototype.forEach.call(slide.querySelectorAll('.qmx-cards,.qmx-static-cards'),markSource);var items=cards.slice(0,4).map(function(c,i){var d=textOf(c);return {detail:d,label:shortLabel(d,i)};}),isDecision=actionable(items),grid=make('div','qmx-scenario-grid qmx-scenario-decisions');slide.setAttribute('data-qmx-scenario-decision-mode',isDecision?'decision':'guided');copy.appendChild(make('div','qmx-scenario-choice-banner',isDecision?'Consider the situation, then choose the response you would take.':'These points are guidance, not alternative choices. Explore each one before continuing.'));copy.appendChild(grid);var coach=panel(copy,isDecision?'Consequence and coaching':'Coach\\'s guidance',isDecision?'Choose a response to reveal the coaching detail.':'Select each point to reveal why it matters.',false),note=instruction(copy,isDecision?'Choose one response to continue':'Explore all '+items.length+' points to continue');function syncGuided(){progress(note,grid.querySelectorAll('[data-qmx-scenario-visited="true"]').length,items.length,'points');}items.forEach(function(item,i){var b=option('qmx-scenario-decision',i,item.label,isDecision?'Choose this response':'Select to explore');b.setAttribute('data-qmx-scenario-visited','false');b.onclick=function(){Array.prototype.forEach.call(grid.children,function(x){x.classList.remove('is-selected');});b.classList.add('is-selected','is-visited');b.setAttribute('data-qmx-scenario-visited','true');coach.head.textContent=isDecision?'Response '+String(i+1).padStart(2,'0'):'Guidance '+String(i+1).padStart(2,'0');coach.detail.textContent=item.detail;if(isDecision){slide.setAttribute('data-qmx-scenario-decision-complete','true');markComplete(note,'Response reviewed • Next is unlocked');}else syncGuided();notify(slide);};grid.appendChild(b);});if(!isDecision)syncGuided();}
  function decorateLabels(slide){if(slide.getAttribute('data-qmx-scenario-label-ready')==='true')return;var eyebrow=slide.querySelector('.qmx-copy .eyebrow');if(!eyebrow)return;var type=String(slide.getAttribute('data-qmx-interaction')||''),label={decision_explore:'Decision point',step_explore:'Guided sequence',compare_reveal:'Compare outcomes',hotspot_explore:'Notice the clues',click_reveal:'Explore and reflect',focus_reveal:'Coach\\'s note'}[type]||'Scenario learning';var current=clean(eyebrow.textContent).replace(/\\s*·.*$/,'');eyebrow.textContent=current+' · '+label;slide.setAttribute('data-qmx-scenario-label-ready','true');}
  function prepare(){slides().forEach(function(slide){if(slide.getAttribute('data-kind')!=='learning')return;decorateLabels(slide);var type=String(slide.getAttribute('data-qmx-interaction')||'');if(type==='focus_reveal')prepareFocus(slide);else if(type==='click_reveal')prepareRevealCards(slide);else if(type==='step_explore')prepareSteps(slide);else if(type==='hotspot_explore')prepareExplore(slide);else if(type==='compare_reveal')prepareCompare(slide);else if(type==='decision_explore')prepareDecision(slide);});}
  function allVisited(list){return list.length>0&&Array.prototype.every.call(list,function(n){return n.getAttribute('data-qmx-scenario-visited')==='true';});}
  function gate(slide){if(!slide)return {required:false,complete:true};if(slide.getAttribute('data-qmx-scenario-complete')==='true')return {required:true,complete:true};var kind=String(slide.getAttribute('data-kind')||'');if(kind==='quiz')return {required:true,complete:Boolean(slide.querySelector('.quiz-option.correct,.quiz-option.incorrect,[aria-checked="true"]'))};if(kind!=='learning')return {required:false,complete:true};var type=String(slide.getAttribute('data-qmx-interaction')||'');if(type==='focus_reveal')return {required:true,complete:slide.getAttribute('data-qmx-scenario-focus-complete')==='true'};var items=slide.querySelectorAll('.qmx-scenario-option');if(type==='decision_explore'&&slide.getAttribute('data-qmx-scenario-decision-mode')==='decision')return {required:true,complete:slide.getAttribute('data-qmx-scenario-decision-complete')==='true'};if(items.length)return {required:true,complete:allVisited(items)};return {required:false,complete:true};}
  function syncNext(){var next=document.getElementById('next-btn'),slide=activeSlide();if(!next||!slide)return;next.removeAttribute('data-qmx-reveal-locked');next.removeAttribute('data-qmx-interaction-locked');var status=gate(slide),locked=status.required&&!status.complete;if(status.required&&status.complete)slide.setAttribute('data-qmx-scenario-complete','true');if(locked){next.disabled=true;next.setAttribute('data-qmx-scenario-locked','true');next.setAttribute('aria-hidden','true');}else{next.removeAttribute('data-qmx-scenario-locked');next.removeAttribute('aria-hidden');next.disabled=false;}}
  function syncSoon(){syncNext();setTimeout(syncNext,0);setTimeout(syncNext,90);setTimeout(syncNext,200);}
  function itemMeta(slide,index,quizNo){var kind=String(slide.getAttribute('data-kind')||'learning');if(kind==='cover')return {type:'Start',label:'Introduction'};if(kind==='final')return {type:'Finish',label:'Course complete'};if(kind==='quiz')return {type:'Knowledge check',label:'Question '+String(quizNo).padStart(2,'0')};var h=slide.querySelector('.qmx-copy h2,h2');return {type:slide.getAttribute('data-qmx-screen-type')==='scenario'?'Scenario':'Learning',label:clean(h&&h.textContent)||('Learning section '+index)};}
  function buildPath(){if(document.querySelector('.qmx-scenario-sidebar'))return;var main=document.querySelector('main');if(!main||!main.parentNode)return;var list=slides();if(!list.length)return;var holder=make('div','qmx-scenario-body');main.parentNode.insertBefore(holder,main);var aside=make('aside','qmx-scenario-sidebar');aside.setAttribute('aria-label','Learning path');var head=make('div','qmx-scenario-sidebar-head');head.appendChild(make('div','qmx-scenario-sidebar-kicker','Learning path'));head.appendChild(make('div','qmx-scenario-sidebar-title',courseTitle()));var prog=make('div','qmx-scenario-sidebar-progress');prog.appendChild(make('span','','Your progress'));prog.appendChild(make('strong','qmx-scenario-sidebar-progress-value','Part 1 of '+list.length));head.appendChild(prog);aside.appendChild(head);var nav=make('nav','qmx-scenario-sidebar-list'),quizNo=0;list.forEach(function(slide,i){if(slide.getAttribute('data-kind')==='quiz')quizNo+=1;var meta=itemMeta(slide,i,quizNo),b=make('button','qmx-scenario-nav-item');b.type='button';b.setAttribute('data-qmx-target',String(i));b.title=meta.label;b.appendChild(make('span','qmx-scenario-nav-number',String(i+1).padStart(2,'0')));var c=make('span','qmx-scenario-nav-copy');c.appendChild(make('span','qmx-scenario-nav-type',meta.type));c.appendChild(make('span','qmx-scenario-nav-label',meta.label));b.appendChild(c);b.appendChild(make('span','qmx-scenario-nav-state',''));b.onclick=function(){navigate(Number(b.getAttribute('data-qmx-target')));};nav.appendChild(b);});aside.appendChild(nav);holder.appendChild(aside);holder.appendChild(main);main.classList.add('qmx-scenario-main');}
  function syncPath(force){var list=slides(),idx=activeIndex();state.maxVisited=Math.max(state.maxVisited,idx);syncNext();if(!force&&idx===state.lastIndex)return;state.lastIndex=idx;var pv=document.querySelector('.qmx-scenario-sidebar-progress-value');if(pv)pv.textContent='Part '+(idx+1)+' of '+list.length;Array.prototype.forEach.call(document.querySelectorAll('.qmx-scenario-nav-item'),function(b){var target=Number(b.getAttribute('data-qmx-target')),active=target===idx,visited=target<=state.maxVisited;b.classList.toggle('is-active',active);b.classList.toggle('is-visited',visited);b.disabled=!visited&&!active;b.setAttribute('aria-current',active?'step':'false');var mark=b.querySelector('.qmx-scenario-nav-state');if(mark)mark.textContent=active?'•':(target<state.maxVisited?'✓':'');});}
  function navigate(target){if(state.navigating||!Number.isFinite(target)||target<0||target>state.maxVisited)return;state.navigating=true;var guard=0;function done(){state.navigating=false;syncPath(true);window.dispatchEvent(new Event('resize'));}function step(){var current=activeIndex();if(current===target||guard++>40){done();return;}var b=document.getElementById(target<current?'prev-btn':'next-btn');if(!b||b.disabled||getComputedStyle(b).display==='none'){done();return;}var before=current;b.click();setTimeout(function(){if(activeIndex()===before){done();return;}step();},45);}step();}
  function seedResume(){var idx=activeIndex();slides().forEach(function(slide,i){if(i<idx)slide.setAttribute('data-qmx-scenario-complete','true');});state.maxVisited=Math.max(state.maxVisited,idx);}
  function install(){if(!document.body||document.body.getAttribute('data-qmx-course-template')!=='scenario-learning')return;prepare();buildPath();seedResume();syncPath(true);window.dispatchEvent(new Event('resize'));var main=document.querySelector('main');if(main){var observer=new MutationObserver(function(changes){var nav=changes.some(function(c){return c.type==='attributes'&&c.attributeName==='class'&&c.target&&c.target.classList&&c.target.classList.contains('slide');});if(nav){prepare();syncPath(false);}else syncNext();});observer.observe(main,{subtree:true,childList:true,attributes:true,attributeFilter:['class','data-qmx-scenario-visited','data-qmx-scenario-focus-complete','data-qmx-scenario-decision-complete']});}document.addEventListener('qmx:scenario-update',syncSoon,true);document.addEventListener('click',function(){setTimeout(function(){syncPath(false);syncNext();},0);},true);window.addEventListener('load',function(){setTimeout(function(){prepare();syncSoon();window.dispatchEvent(new Event('resize'));},0);});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
</script>`;
}

function inject(html, templateId) {
    let source = String(html || '');
    if (!source || safeAttr(templateId) !== 'scenario-learning') return source;
    if (!source.includes(STYLE_ID)) source = source.replace('</head>', `${style()}\n</head>`);
    if (!source.includes(SCRIPT_ID)) source = source.replace('</head>', `${script()}\n</head>`);
    return source;
}

async function applyScenarioLearningRuntimeToZip(zipBuffer, analysis) {
    if (String(analysis?.templateBinding?.templateId || '') !== 'scenario-learning') return zipBuffer;
    const zip = await JSZip.loadAsync(zipBuffer);
    const htmlNames = Object.keys(zip.files).filter((name) => !zip.files[name].dir && /\.html?$/i.test(name));
    let changed = false;
    for (const name of htmlNames) {
        const html = await zip.file(name).async('string');
        const patched = inject(html, 'scenario-learning');
        if (patched !== html) {
            zip.file(name, patched);
            changed = true;
        }
    }
    return changed
        ? zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } })
        : zipBuffer;
}

module.exports = { STYLE_ID, SCRIPT_ID, applyScenarioLearningRuntimeToZip, inject, script, style };
