name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install server dependencies
      run: npm install --prefix server

    - name: Install client dependencies
      run: npm install --prefix client

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build client
      run: npm --prefix client run build

    - name: Run server unit tests
      run: npm --prefix server test

    - name: Run E2E tests
      run: npm run test:e2e
